Questie/Questie.lua
I use the old sane Player values if the player has the map opened on another zone, and will continue to update as soon as he switches back or closes the map.
The reset zone i switched to only force a reset if the mapID is -1 (Aka strange / null / don't exist)
Not 100% tested BUT should work, you are more familiar with the codebase hopefully you can look through it and know if this will fuck up anything else.
=> Fixed the map resetting when switching zones in cartograhper.

!Questie/Questie.lua, !Questie/QuestieNotes.lua
* Improved the WorldMap Quest tool tips by adding Quest Level, Quest
Started by, Quest Finished by and an OnClick usage note for manually
finishing quests.
* Added an OnClick function to manually finish quests via the WorldMap
along with an Auto-Toggle routine that refreshes the map and makes the
icon instantly disappear upon manual completion.
* For quest chains with more than one step I added a Popup Dialog that
accepts user input so they can select which step to complete. Quest
chain steps are still reported via the chat window since the popup only
accepts two button inputs or an edit box.
=> Tooltips & OnClick

!Questie/!Questie.toc, !Questie/QuestieNotes.lua
A bug was reported on the Nostalrius forums - there was some frame code
that was creating double popups preventing new one's from appearing
properly. Fixed.
During my debug I found another bug in the "refresh code" that caused
Questie to disable itself in certain situations. Fixed.
I added a 10 sec timeout to the popup dialog in case it doesn't appear
on a users screen to handle poorly coded evil add-on's that might
prevent it from being displayed properly. Grrrrrr.... - A fail safe of
sorts.
Updated TOC to reflect new version
=> Bug Fix & Updated TOC

!Questie/QuestieTracker.lua
I think this should work better with SetClampedToScreen().
The old implementation doesn't seem to handle left/right/bottom corners properly in WoW window mode, and also if you barely move the questie frame near the top window corner, the whole frame will disappear untill a /reload.
=> Fix dragging frame off screen

!Questie/astrolabe/Astrolabe.lua
- This fixes a small deviation in note display on the continent and
world maps due to the old data being for TBC.
- Removed offset related hack fix loop.
- Disabled the error output when mapData gets zeroed. After the removal
of the TBC zones the line was throwing an error instead of posting a
chat message.
- Continent offsets and worldmap size are still everyones best guess but
zone data is correct.
=> Updated Astrolabe data

!Questie/Database/addendum.lua, !Questie/Modules/QuestieNotes.lua
Updated the quest database with the addition of "questLevel" for each quest, which is the actual level of the quest, not the required level.
Removed/renamed/fixed some quests in the database.
Updated QuestieNotes to now have the available/complete quest tooltips show the questLevel instead of the minimum level.
=> Added actual quest levels to use for tooltips.

!Questie/Modules/QuestieNotes.lua
Before, quests in the same location would overwrite each other on the map. Now you can see all the available quests.
=> Quality of Life change: Quests in the same location now combine their tooltips.

!Questie/Questie.xml
Instead of using a "static" number value for the button position, one could anchor the button to the dropdown menu.
I believe, the button should be on the same position, no matter what scale the WorldMapFrame is.
I recently pushed some WorldMapFrame mod to pfUI (https://github.com/shagu/pfUI/commit/1bbf47ad2b3ec4de966ab62fd05901add3a8bb87) nothing special but I've seen that the Questie_Toggle button is out of place, just because of a changed map scale. After searching around the web, I've seen that the same has happened to modUI from @obble.
I tested this on a default Wow Map, with pfUI's Map and with Cartographer. All seem to be fine now.
This is just a suggestion, but it would help us addon developers to avoid "if IsAddOnLoaded'!Questie' then"-hackfixes.
Cheers,
Shagu
=> Anchor of the Questie_Toggle button

!Questie/Database/addendum.lua
Seems that this quest required level was changed sometime after 2006 to level 1. Nevertheless according to [AoWoW](http://db.vanillagaming.org/?quest=579) the quest should have a required level of 5. This also seems to match what most vanilla server's databases have.
=> Corrected reqlevel of quest Stormwind Library

!Questie/Modules/QuestieNotes.lua, !Questie/Questie.lua
Quests used to be grouped together if they have exactly the same coordinate. Now they are clustered by distance to each other using a Hierarchical Clustering algorithm. The clustering distance for the world map is set to 0.025 (or 2.5 in terms of coordinates that are shown to players), while the distance for the minimap is set to 0 so that the position of the quest is as accurate on the minimap is possible. The algorithm also limits the cluster size to 5 so that too many quests don't get grouped together and become overwhelming to the tooltip that displays their info, with the exception of quests that are at a distance of 0 from each other which always get clustered together. These values can easily be tweaked in the code, which should make it possible to easily make them …
=> Replaced primitive exact coordinate based grouping with distance based Hierarchical Clustering.

!Questie/Questie.lua
There has been an issue with Cartographer that requires the user to reload
the UI in order to see Questie's quest objective markers on the map. By
updating Questie when a quest is accepted this issue is fixed.
=> Add event handler for "QUEST_ACCEPTED" events

!Questie/astrolabe/Astrolabe.lua
The old function will result in nil errors for every addon that includes the pfUI API but isn't pfUI itself. This PR will use the pfUI.minimap field which is only existing if pfUI is active and has enabled minimap support.
=> Use a more convenient way to detect pfUI minimap

!Questie/Database/addendum.lua
* Quest 794 (Burning Blade Medallion) is only available after Quest 792 (Vile Familiars)
=> Fix required quests for quest 794

!Questie/astrolabe/Astrolabe.lua
Makes the note position on square minimap border dependent on relative xy distance.
This means that orienting yourself toward the marker on the minimap should orient you toward the objective, which is not the case currently.
=> Improve note position outside square minimap

!Questie/Modules/QuestieInterfaceTexts.lua, !Questie/Modules/QuestieOptions.lua, !Questie/Modules/QuestieOptions.xml
#Adds the hide objectives option into the setings GUI.
The setting is the one added in ee4e60999549c1e466fd59d13d01e854344e00ff
It's an enhancement to the existing gui issue #315
=> Added 'hide objectives' option into settings gui

Modules/QuestieNameplate.lua, Questie.lua, QuestieDev-QuestieClassic.toc
Saw in the Questie Discord a request for placing a quest market on the mobs nameplates that are objectives for quests.  Took a shot at it and working on my Lua / addon skills.  Uses the QuestieTooltip data to add a small ! icon to the left of the nameplates for all creatures that are objectives. 
Current FramePool didn't seem to support so wrote a quick new one.  Some cleanup required.
=> Questie classic

Modules/QuestieFramePool.lua, Modules/QuestieNameplate.lua, Modules/QuestieQuest.lua, Modules/QuestieTooltips.lua, Questie.lua
Fixed 2 issues with nameplate icons.
1.) Icons will now automatically remove from quest mobs once the quest objectives are complete (There is a few second delay on this based on, I believe, the quest API latency issues)
2.) On a multi-mob quest, when you complete the objective for a single mob, other mobs on the same quest will still show their icons. 
** Note: The weird changes to other files is from updating my fork and it seemed to cause issues but they should be the same changes that are currently in the QuestieClassic branch from Logon.
=> Questie Nameplate Icons -- Objective issues

Modules/QuestieMap.lua, Questie.lua
Updated logic to be able to fade the icons over the player on the minimap too to avoid hiding in-game nodes (such as if an herb or ore node is under an objective icon).    This can be enabled / disabled from the options.
=> Fade over player minimap

Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua, Modules/QuestieFramePool.lua, Modules/QuestieMap.lua, Modules/QuestieNameplate.lua, Questie.lua
Updated the config window and options. This commit includes:
1.) Added remap function for "Icon of Player" fade smoothing
2.) Added ability to configure distance and fade amount of icons over player
3a.) Update the minimap icon tooltip and toggling
3b.) Updated AceConfigDialog library to include an onclose callback setter to updating the toggle variable to avoid toggle inconsistencies. 
4.) Updated config window to have better defined category tabs and spacing.
=> Update to Config Window and Options

Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua, Modules/QuestieQuest.lua, Questie.lua
This should fix the issue with the Ace callback to toggling the config window. It removes the toggling feature from the minimap icon, must be closed via the close button or esc key.
This should address issue: #590
=> Fixed to config window errors.

Modules/QuestieCoordinates.lua, Questie.lua
As suggested by user Shelfen on Discord.  Ability to choose the decimal precision for the coordinates of player and cursor on the map (not minimap due to space limitations)
=> Ability to set map coordinate precision

Questie.lua
Update to Map Button toggle on some map addons that may cause issues.  Or those who don't want the button on their map.  Added a slash command and a minimap toggle feature (in addition to the feature on the questie config pane) in the event the map button is hidden. 
Cases where the button doesn't work with the frame should still be reported and the button's location can be adapted to those addons and any custom frames they may use.
=> Update to Map button toggle and more slash commands. 

Modules/QuestieQuest.lua
See #637 
Fix for other languages. When the ObjectiveData doesn't exist, fill it with default objectiveData.
=> Quick fix for other languages

Modules/QuestieFramePool.lua
Textures by default will snap to a pixel grid instead of using sub-pixel rendering, which does produce a sort of wobbling icon effect when textures are being animated/moved over the minimap.
Disable the snapping to get a smoother icon movement on the minimap.
=> Disable texel snapping to reduce icon wobbling on the minimap

Locale/enUS/config.lua
Updated ENABLE_AVAILABLE_DESC  text to use "available quest" instead of "quest turn-in"
=> Updated ENABLE_AVAILABLE_DESC 

Database/corrections.lua
I missed two quests in #728
Those two quests added in this PR are the once that reward the actual "Tome of Divinity" which will start another quest to visit the trainer.
=> Add missing breadcrumb quests to fix #703

Modules/QuestieQuest.lua
When the player level is 10 and the minimum level filter is 1, quests with level 9 should be visible. Similarly, when the maximum level filter is 1, quests with level 11 should be visible.
I've tested this with [a level 43 quest](https://classic.wowhead.com/quest=2342/reclaimed-treasures), a level 33 character and the maximum level filter ("how many levels above your character to show") set to 10. Before the change, the quest doesn't show up. After the change, it does.
=> Fix off-by-one issue level filter.

Database/corrections.lua
The "Buring Blade X" mobs need to be hurt before using an quest item which makes the mobs drop the items required for the quest of #751 
This PR adds those mobs to drop the item which is kind of a work around, but imo better than no objectives shown.
=> Add Burning Blade members to drop gems to fix #751

Modules/QuestieTracker.lua
Currently, when a user opens the quest log via shift clicking the QuestieTracker, they are unable to close it using the escape button after. This pull request address that.
=> Fixed quest log not closing on escape press.

Questie.lua
Small change I've had active locally for a while:
If `WorldMapContinentDropDown` is hidden, move the `Questie_Toggle` button to be left of the `WorldMapFrameCloseButton` instead.
There are addons that hide parts of the World Map UI, most notably the `WorldMapFrame.BorderFrame` and/or buttons/dropdowns on it, making the "Hide Questie"/"Show Questie" button appear to float in a weird position. This solves the issue, at least for addons that do still show the close button.
=> Change position of Map button when continent dropdown is hidden

Modules/Quest/QuestieQuest.lua, Modules/QuestieEventHandler.lua
Fixes #1433
Either of these changes in isolation would fix the issue.
Either repeatable quests should be considered `complete` or we should be laxer about updating them. 
I'm not entirely sure of the structure of the `Questie.db` object or what the `Questie.db.char.complete` map is meant to track, so this seems kind of hack-ish to me. Open to any feedback here.
=> Fixes tracking of repeatable quests

Database/Corrections/QuestieItemFixes.lua
As the title says, `Thick Yeti Fur` does **not** drop from `Ice Thistle Matriarch` or `Ice Thistle Patriarch`, so remove these two from the list.
=> Thick Yeti Fur does not drop from Ice Thistle Matriarch/Patriarch

Modules/QuestieCoordinates.lua
Both Questie and Coordinates addon's try to write map coordinates.
This change just lets the Coordinates addon do it's thing if it's enabled.
=> Fix bug with Questie and Coordinates addons

Modules/Auto/QuestieAuto.lua
As discussed in the questie discord i changed the if statement to be an elseif.
=> Fix error thrown when auto accepting quests not in the database

Database/Corrections/QuestieItemFixes.lua
@Rillant reported this in Discord, and another person in-game reported this to me earlier in the week that they were showing up on the elementals. This should fix the issue.
=> Fix for Twilight Tablet drops

Database/Corrections/QuestieItemFixes.lua
These quests require stones from these pillars to call the dragons that you need to kill. Adding the stones / pillars in.
https://classic.wowhead.com/quest=793/broken-alliances
https://classic.wowhead.com/quest=717/tremors-of-the-earth
Pillar of Amethyst: 81,63
https://classic.wowhead.com/object=2858/pillar-of-amethyst
https://classic.wowhead.com/item=4843/amethyst-runestone
Pillar of Opal: 72,66
https://classic.wowhead.com/object=2848/pillar-of-opal
https://classic.wowhead.com/item=4844/opal-runestone
Pillar of Diamond: 83,33
https://classic.wowhead.com/object=2842/pillar-of-diamond
https://classic.wowhead.com/item=4845/diamond-runestone
=> Fixes for 2 Quests - Broken Alliances & Tremors of the Earth

Database/Corrections/QuestieItemFixes.lua
- Not showing right spots for all the crabs.
https://classic.wowhead.com/quest=1261/marg-speaks
https://classic.wowhead.com/item=5942/jeweled-pendant
https://classic.wowhead.com/npc=4405/muckshell-razorclaw
https://classic.wowhead.com/npc=4401/muckshell-clacker
https://classic.wowhead.com/npc=4404/muckshell-scrabbler
https://classic.wowhead.com/npc=4402/muckshell-snapclaw
https://classic.wowhead.com/npc=4403/muckshell-pincer
https://classic.wowhead.com/npc=14236/lord-angler
DB:
[5942]={"Jeweled Pendant",{1261,1262},{4401,4402,4403,4404,4405,14236,4401,4402,4403,4404,4405,14236},{}},
=> Fixes for Marg Speaks Quest

Database/Corrections/QuestieNPCFixes.lua
Grenka spawns after you loot some chests, but we didn't have her location. Adding it, without it, there's no indicator on the map.
* Test of Endurance - Quest - World of Warcraft || https://classic.wowhead.com/quest=1150/test-of-endurance
* Grenka Bloodscreech - NPC - World of Warcraft || https://classic.wowhead.com/npc=4490/grenka-bloodscreech
* Grenka's Claw - Item - World of Warcraft || https://classic.wowhead.com/item=5843/grenkas-claw
=> [quest] Fixes for [30] Test of Endurance

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Speak with Shoni" as exclusive to "Underground Assault"

Database/Corrections/QuestieQuestFixes.lua
This will prevent "Greatfather Winter is Here!" from showing in Undercity for Alliance.
=> [quest] Fixed starting NPC of "Greatfather Winter is Here!"

Database/Corrections/QuestieObjectFixes.lua
Since we can't draw icons om mapids without a map we should revert back to Feralas zoneid
``[178224] = {"Dire Pool",nil,nil,{[357]={{58.94,35.97}``
from objectDB
=> [quest] Update object locations of "Dire Pool"

Database/Corrections/QuestieItemFixes.lua
[[46] Saving Yenniku (592)] -- missing objectives on map, add soul gem / Filled Soul Gem
Saving Yenniku - Quest - World of Warcraft || https://classic.wowhead.com/quest=592/saving-yenniku
Filled Soul Gem - Item - World of Warcraft || https://classic.wowhead.com/item=3913/filled-soul-gem
Yenniku - NPC - World of Warcraft || https://classic.wowhead.com/npc=2530/yenniku
[592] = {"Saving Yenniku",{{2519,},nil,nil,},{{2497,},nil,},30,46,178,nil,{"Bring the Filled Soul Gem to Nimboya.",},nil,{nil,nil,{{3913,nil},},nil,},3912,nil,{591,},{593,},nil,nil,33,nil,nil,nil,nil,nil,nil,nil,nil,},
[2530] = {'Yenniku',1902,1902,41,41,0,{[33]={{39.02,58.35},},},nil,33,{593,},{593,},28,nil,"Darkspear Hostage",2
https://github.com/AeroScripts/QuestieDev/pull/2107
=> [quest] Fixes for Saving Yenniku

Database/Corrections/QuestieQuestFixes.lua
* Tremors of the Earth - Quest - World of Warcraft || https://classic.wowhead.com/quest=717/tremors-of-the-earth
* Broken Alliances - Quest - World of Warcraft || https://classic.wowhead.com/quest=793/broken-alliances
=> [quest] Updates for Tremors of the Earth and Broken Alliances

Database/Corrections/QuestieQuestFixes.lua
Setting objective to the actual NPC (for mouseover) instead of an invisible trigger.
=> [quest] Updated objective locations for "Dearest Natalia"

Database/compiler.lua, Modules/Libs/QuestieLib.lua, Modules/QuestieEventHandler.lua
I think it's better to grab the Version field defined in toc, rather than parsing the title.
=> Get version string without parsing title

Database/Corrections/QuestieQuestFixes.lua
'preQuestSingle' to not have it shown as repeatable all the time in Duskwood. 
'exclusiveTo' because it's unavailable after completion of 253.
'specialFlags' because it's used to summon the boss. Can be done more than once (repeatable).
Partly fixes #2173
=> [quest] Marked "Digging Through the Dirt" as repeatable

Libs/ZoneHelper/ZoneHelper.lua
This should help avoid errors loading when other addons have already defined this library.
=> Handle already loaded ZoneHelper

Database/Corrections/QuestieQuestFixes.lua
Added Un'Goro Soil (3761) to the breadcrumbs since all three will be disabled when you complete it.
=> [quest] Marked "Assisting Arch Druid Runetotem" as breadcrumb quest

Database/Corrections/QuestieQuestFixes.lua
Added Un'Goro Soil (3764) to the breadcrumbs since all three will be disabled when you complete it.
=> [quest] Marked "Assisting Arch Druid Staghelm" as breadcrumb quest

Database/Corrections/QuestieQuestFixes.lua
These open up after 918, not 919.
=> [quest] Fixed pre quest for "The Shimmering Frond"

Database/Corrections/QuestieQuestFixes.lua
997 "Denalan's Earth" is not required for 918. Completing 918 does NOT disable 997 "Denalan's Earth".
=> [quest] Marked "Denalan's Earth" as breadcrumb quest

Modules/QuestieEventHandler.lua
Fixes #2198 #2124.
Description table is not 'nil' but empty after 6.0 compression.
=> [fix] Complete "automatic completion" quests when turned in

Database/Corrections/QuestieQuestFixes.lua
Looks like both are offered at the same time so no ``exclusive to`` needed on followup.
https://classic.wowhead.com/quest=7816/gammerita-mon#comments:id=3191920
#2247
=> [quest] Fixed requirements for "Gammerita, Mon!"

build.py
Resolve the following build failure resulting from versionTag containing a hyphen.
```
Traceback (most recent call last):
File "build.py", line 205, in <module>
main()
File "build.py", line 97, in main
versionDir, addonDir, zipName = setArgs()
File "build.py", line 55, in setArgs
version, nrOfCommits, recentCommit = getVersion()
File "build.py", line 172, in getVersion
versionTag, nrOfCommits, recentCommit = tagString.split("-")
```
=> Support hyphens in the versionTag.

Modules/Quest/QuestieQuest.lua
Added code to handle "special" quests like "The Nightmare's Corruption" to show objective correctly for quests where multiple objectives have the same text.
Fixes #2308
=> [fix] Fix objective locations of "The Nightmare's Corruption"

Database/Corrections/QuestieItemFixes.lua
Removed NPC drops for Silithid eggs.  
```
[5058] = {
[itemKeys.npcDrops] = {},
},
```
=> Fixes for [22] Egg Hunt

Modules/Tooltips/Tooltip.lua
Before we removed the tooltip key wholesale, now doing a more specifc removal not to lose the whole object!
The fix has not been tested fully but the code looks sane enough.
=> Tooltip Removal Fix.

Modules/QuestieEventHandler.lua
"Instant" quests (I don't know correct term) won't fire QUEST_REMOVED and so they pollute latestTurnedInQuestIds[]. This breaks next quest turn ins / completions. Visible to users mostly so that quest markers won't disappear from the map / the minimap.
There was also missing a call to add these "instant" quest completions to Questie Journey. I choosed to go via ready helper function for hopefully easy future  code maintenance. Downside for this is use of timer in helper function until server returns the quest to be completed status.
=> Fix quest turn in for instant quests which don't fire QUEST_REMOVED

Database/Corrections/TBC/tbcNPCFixes.lua
@drejjmit Here are those fixes to alliance bonfire quests in Azeroth (not Outland) as I promised on Discord. Only some minor location changes to few of the Honor the Flame -quests. Desecrate this Fire! were okey.
I also checked quests for alliance in horde capitals.
XP and Gold gains are wrong, but I have no idea how to fix those. (Is it worth to create an issue?)
=> [quest] Some fixes to Midsummer quests in TBCC 2021

Database/Corrections/QuestieEvent.lua, Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/TBC/tbcNPCFixes.lua, Database/Corrections/TBC/tbcQuestFixes.lua
Adds ice stone locations to summon and kill quest objective mob.
Adds npcs for finishing quests (turn-in)
Adds required prequest.
Adds quest giver and minimum level for highest level version of the quest. Minimum level is 65 as a safe guess for now.
=> [bcc][quests] Midsummer Striking Back quest fixes

Modules/Tracker/QuestieTracker.lua
The value of status can be a number for some reason, this is just a hacky fix to prevent the error completely locking up the questie tracker.
=> Hacky fix for status exception

Database/Corrections/TBC/tbcQuestFixes.lua
Add level requirement 65 for quest "Ahune, the Frost Lord" 11955.  Currently it is showing available to lowbies.
=> [quest] More fixes to midsummer quests in BCC

Modules/Libs/QuestieHash.lua, Modules/Libs/QuestieLib.lua, Modules/Quest/QuestEventHandler.lua, Modules/Quest/QuestieQuest.lua
As little changes as possible. A bit speed up before beta testing. Looks almost bugless while playing. Clicking quest log entries to enable / disalbe questie tracker tracking bugs a bit by affecting wrong quest sometimes.
I have not yet reviewed QuestEventHandler.lua latest version for bug & stuff.
=> for PR #3127: loop less in quest objects. more objective tries

Modules/FramePool/QuestieFrame.lua
Show quest complete icons on maps for following quest type icons even other icons for those types are disabled
- Repeatable
- Event
- Dungeon
- Raid
- PvP
- AQWarEffort
I'm not sure if showing some of those types are OK as npc won't be there anymore necessary. **Opinions?**
Also using more local variables instead of searching from tables
=> [fix] Show quest complete icons and objectives icons if not specially disabled

Database/Corrections/TBC/tbcQuestFixes.lua
fixes #3130
-The quests can be done all way even at exalted as these ones aren't repeatable quests.
-Add either of 10551,10552 to requirement as player can change from Aldor->Scryers or other way.
=> [quest] [fix] Aldor/Scryers rep quests requirements

Database/Corrections/TBC/tbcQuestFixes.lua
fixes #2853
I also checked other factions cloth turnins in DB vs. https://tbc.wowhead.com data.
=>  [quest] [fix] Exodar, Darnassus cloth rep turnins

Modules/Quest/QuestieQuest.lua, Modules/QuestiePlayer.lua, Modules/Tracker/QuestieTracker.lua
Don't try to assign stuff into global `_`. Wow doesn't like it:
`Global variable _ tainted by Questie - Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1056 PopulateQuestLogInfo()`
This was somewhat mind blown to me.
I used `^\s*((?!(local)|(for)|(function)\s).)*?[,\s]+_[,=\s]+` for search.
**The PR is not tested in game. Only done changes in editor.**
=> [fix] Don't taint global variable _

Modules/VersionCheck.lua, cli.lua
Review of VersionCheck.lua
-  Remove addon version check as it didn't do its job and should be soon unnecessary once WoW supports full addon reloading at `/reload`. Hopefully CurseForge gets their shit together too and release addon manager supporting multiple tocs okey.
- Added extra check that Questie really is run from `Questie` folder and with that name. So users won't try to run multiple at once. Even double Questie global is already checked.
- Enable retail game check which was most likely unintentionally left disabled by old development testing while getting retail/tbc zoneIDs.
=> [fix] Remove addon version check. Add addon name check. Enable retail game check

Modules/Tracker/QuestieTrackerUtils.lua
ShowUIPanel(  ) is protected, so it can't be used while in combat.
Calling QuestLogFrame:Show() directly would mess up UI.
Select the quest in questlog anyway and try scroll to it.
Scrolling has old bug if the quest is inside collapsed, but I didn't find good way to fix it now.
If we couldn't open quest log, tell user open it themself.
Fixes #2854
Changes aren't tested  with other quest log addons mentioned in code
=> [fix] Don't open Quest Log in combat from tracker.

Modules/Tooltips/TooltipHandler.lua
Old-old itemId parsing from itemLink has always took wrong field from parse. This was later fixed for TBCC in new if-branch and Era was left as is.
This PR removes Era if-branch and uses correct for both classic versions.
=> [fix] [Era] Getting itemId from tooltip's itemLink

Modules/Tracker/QuestieTracker.lua
Looting a quest objective item triggers already a quest watch event and/or questlog events. Those run tracker update.
BAG_NEW_ITEMS_UPDATED won't fire when an old item stack gets new items into it. So it is useless for most quest objectives.
Helps little for #3120
Helps little for #2801
=> [fix] fps drop at looting

Modules/QuestieAnnounce.lua
Interpret false correctly. Earlier it was interpreted as not cached.
Check questId > 0 only before caching it.
=> Improve ItemLooted itemCache

Database/Corrections/QuestieEvent.lua
Support different seasonal event dates or fully missing event per expansion.
Fix Harverst Festival dates for year 2021.
Disable Brewfest on Classic Era.
Squash merge with this commit as message.
=> Support different seasonal event dates per expansion (#3174)

Database/compiler.lua
Replace table.insert with a lot faster table[i] = foo
Use known table size in few places
=> Major performance improvements to compiler readers

Database/Corrections/QuestieEvent.lua, Database/Corrections/TBC/tbcItemFixes.lua, Database/Corrections/TBC/tbcQuestFixes.lua
Ally version has object instead of item as starter - and id was wrong. Fixes #3179
Horde had a version with wrong quest id.
Not sure if objectivesText are correct as I haven't done quests ingame.
=> [quest] Fix ally and Add missing horde "Brew of the Month Club"

.vscode/settings.json, Modules/Map/QuestieMapUtils.lua, Modules/Quest/QuestieQuest.lua, Modules/Quest/QuestieQuestPrivates.lua
This changes a lot more than I inteded originally. Focuses into QuestieQuest:PopulateObjective( ) and functions it uses, but includes also performance practices elsewhere in modified files.
Includes also a bug fix to use all spawn locations of quest object. Previously only one at same floor(distance) from center was included regardless of direction.
Functionality should be otherwise same. Except now it uses non-floored distances in sorting. Should check with larger data set if floored would be faster, but on my test case non-floored is faster.
=> Performance improvements to map icons generation

Database/Corrections/Classic/classicQuestFixes.lua
NPC `100` "Gruff Swiftbite" does not directly starts quest `123` "The Collector", it is obtained from item `1307` "Gold Pickup Schedule" drop solely
=> Fix quest 123 "The Collector" starters

Database/Corrections/QuestieEvent.lua, Database/Corrections/QuestieQuestBlacklist.lua
Checked all quests in `QuestieEvent.lua` (excluding war effort) exists in `QuestieQuestBlaclist.lua`. 
* Add "Darkmoon Blessings Deck" (10938) to DMF event quests. It's a new quest in TBC p3. It was already blacklisted.
* Remove duplicate entry of "Darkmoon Lunacy Deck" (10941) from event quests.
* Blacklist Horde "Brew of the Month Club" (12421)
* Blacklist "Insult Coren Direbrew" (12062).
Fixes #3240
* Blacklist "Let the Fires Come!" (12135) (12139)
Fixes #3238
=> [quest] Blacklist all event quests

Modules/Tracker/QuestieTrackerPrivates.lua
Fixes #3266
OnDragStop uihandler event won't give button argument.
I would like to remove also IsMouseButtonDown altogether, because drag event is registered only for left button, and also remove \*Drag\* checks, but I'm afraid of possible bugs as I am not sure why those all are there even checking just .isMoving would be enough.
=> Fix Tracker stuck on mouse with multiple buttons

Database/Corrections/QuestieEvent.lua
Current code never detects event be active if the event starts and ends at different years - i.e. start month is larger than end month.
```lua
if (month < startMonth) or -- Too early in the year
(month > endMonth) or -- Too late in the year
```
example:
```lua
startMonth = 12
endMonth = 1
(12 < 12) or (12 > 1) -- evaluates always to true -> event not active
```
This PR fixes logic to work also in this case.
Also fix to show the Winter Veil Gift new in TBC only starting from christmas day.
=> [fix] Detect event spanning across year cange

Modules/Quest/QuestEventHandler.lua, Modules/QuestieInit.lua, Modules/QuestieValidateGameCache.lua, Questie-BCC.toc, Questie-Classic.toc, Questie.lua
- Validate game's cached quest log asyncronously
- Make Questie's init flow to pause and wait valid quest log for parts needing it.
- Has QuestieInit.lua modified to support easier refactor of whole init flow, which is a bit mess now (even without PR-3111).
Note: Required test for future in PTR when blizzard is going to release a new phase - as those usually may have bigger changes to how things work.
1. Delete game cache. For example the directory: `...\_classic_era_\Cache\`.
2. Login a character having many quests in quest log.
3. /reload
4. Logout and login the character again.
5. Login another character having 0 quests in quest log. (Or if you use same character, then delete game cache again after emptying the quest log).
6. /reload
7. Logout and login the character again.
=> Refactor Game's cached quest log validation

LibsOnlyClassic/LibQuestXP/CHANGELOG.md, LibsOnlyClassic/LibQuestXP/LibQuestXP.lua, LibsOnlyClassic/LibQuestXP/LibQuestXP.toc, LibsOnlyClassic/LibQuestXP/libs/LibStub/LibStub.toc, LibsOnlyTBC/LibQuestXP/CHANGELOG.md, LibsOnlyTBC/LibQuestXP/LibQuestXP.lua, LibsOnlyTBC/LibQuestXP/LibQuestXP.toc, LibsOnlyTBC/LibQuestXP/libs/LibStub/LibStub.toc, Modules/Tooltips/MapIconTooltip.lua
The lib has build in support for SoM quest xp bonus,
so Questie's code for +40% is removed now.
Extra bonus xp for elite and dungeon quests is still missing.
Questie modifications of library's TBC version removed.
It was modified to use `QuestiePlayer:GetPlayerLevel()` while Questie was in debug mode.
=> Update LibQuestXP to 1.0.8 and 2.0.3

Modules/Tracker/QuestieTracker.lua
If player gets into combat during the 2s timer, then QuestieCombatQueue was useless. So start timer first and add into QuestieCombatQueue at end of timer.
=> [fix] First Tracker update if starting combat middle of it

Modules/Quest/QuestieQuest.lua
Backported fix from quest-event-refactor. Really an edge case.
=> [fix] Get next from correct table

Modules/Quest/QuestEventHandler.lua
UNIT_FACTION didn't fire always when needed and frequently at
wrong order for us compared to QUEST_LOG_UPDATE.
=> Change back to use CHAT_MSG_COMBAT_FACTION_CHANGE event

Database/Corrections/QuestieItemBlacklist.lua
Adding a few more TBC items to reduce clutter around "commodity" items that can be readily obtained from the Auction House. Also cleaned up TBC list by sorting by Item ID.
=> Suggestions to Remove Common Auction House Items to Reduce Map and Tooltip Clutter

Database/Corrections/Classic/classicItemFixes.lua
Fixes item [Thunder Ale (2686)](https://classic.wowhead.com/item=2686/thunder-ale) not showing as quest marker for quest [Distracting Jarven (308)](https://classic.wowhead.com/quest=308/distracting-jarven).
Also added missing npcDrops for item [Rhapsody Malt (2894)](https://classic.wowhead.com/item=2894/rhapsody-malt) while at it.
=> Fix item 2686 Thunder Ale not showing as quest marker

Database/Corrections/Classic/classicQuestFixes.lua
The druid quest Heeding the Call was messed up a little. This should fix them all.
- Fix quest [Heeding the Call (5923)](https://classic.wowhead.com/quest=5923/heeding-the-call)
- started by [Denatharion (4218)](https://classic.wowhead.com/npc=4218/denatharion)
- Fix quest [Heeding the Call (5924)](https://classic.wowhead.com/quest=5924/heeding-the-call)
- started by [Theridran (5505)](https://classic.wowhead.com/npc=5505/theridran)
- Fix quest [Heeding the Call (5925)](https://classic.wowhead.com/quest=5925/heeding-the-call)
- started by [Kal (3602)](https://classic.wowhead.com/npc=3602/kal)
- Fix quest [Heeding the Call (5926)](https://classic.wowhead.com/quest=5926/heeding-the-call)
- started by [Innkeeper Pala (6746)](https://classic.wowhead.com/npc=6746/innkeeper-pala)
- Fix quest …
=> Fix druid quest Heeding the Call

Database/Corrections/Classic/classicQuestFixes.lua
Fix warrior quest [Elanaria (1684)](https://classic.wowhead.com/quest=1684/elanaria)
- startedBy [Moon Priestess Amara (2151)](https://classic.wowhead.com/npc=2151/moon-priestess-amara), [Kyra Windblade (3598)](https://classic.wowhead.com/npc=3598/kyra-windblade) and [Sentinel Elissa Starbreeze (3657)](https://classic.wowhead.com/npc=3657/sentinel-elissa-starbreeze)
=> Fix warrior quest Elanaria

Database/Corrections/Classic/classicQuestFixes.lua, Database/Corrections/TBC/tbcQuestFixes.lua
Changed zoneOrSort to SEASONAL from SPECIAL
Wrong sortKey stops Questie Initializing on Low FPS while
the event is active. So there must be also some racecondition somewhere.
Needs fixing: New Children's Week quests on TBC.
Fixes #3426
Fixes #3429
=> [quest] Fix Children's Week quests zoneOrSort

Database/Corrections/Classic/classicItemFixes.lua
Item [Moss-twined Heart (5179)](https://classic.wowhead.com/item=5179/moss-twined-heart) is dropped by npc [Blackmoss the Fetid (3535)](https://classic.wowhead.com/npc=3535/blackmoss-the-fetid)
=> Fix item Moss-twined Heart (5179) npc drops

Database/QuestieDB.lua, Localization/l10n.lua, Modules/Auto/Privates.lua, Modules/Auto/QuestieAuto.lua, Modules/Journey/tabs/QuestsByZone/QuestsByZone.lua, Modules/Libs/QuestieLib.lua, Modules/Map/QuestieMap.lua, Modules/Network/QuestieComms.lua, Modules/Options/QuestieOptions.lua, Modules/Quest/QuestieQuest.lua, Modules/QuestLinks/Link.lua, Modules/QuestieEventHandler.lua, Modules/QuestieMenu.lua, Modules/QuestieReputation.lua, Modules/QuestieValidateGameCache.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/Tooltips/Tooltip.lua, Modules/Tracker/QuestieTracker.lua
Remove some string concatenates from debug calls
to increase performance.
Also fix few calls missing debug level.
Also change GetTooltip DEVELOP -> SPAM.
Also edit some of the messages.
=> Remove some string concatenates from debug calls

Modules/QuestieMenu.lua
Fixes [Gubber Blump (10216)](https://classic.wowhead.com/npc=10216/gubber-blump) can train fishing. He's not a conventional trainer, but one of its gossip is to train fishing when you don't have the profession. He then becomes a vendor after you trained fishing from him.
I am not sure if this is the proper way to fix this, please let me know if you want a different fix.
=> Fix Gubber Blump can train fishing

Modules/QuestieStream.lua
For stream type "raw", which Questie's database uses:
Don't use expensive `lshift(x, bits)` but `x * 2^bits`
Don't call `:ReadByte()` to extract one byte at time from the string, but use directly `stringbyte(string, start, stop)` to get all bytes by a single string access.
Use a local variable to access `stream._pointer` less times.
Use `return someFunction()` if return value is got from a single function. Lua can optimize this.
=> [fix] Improve performance of Database

Modules/QuestieStream.lua
For stream type "raw", which Questie's database uses:
Don't call `:ReadByte()` to get length of asked string, but inline the function.
Use a local variable to access `stream._pointer` less times.
Avoid if-branch when possible: `string.sub(text, start, stop)` already returns `""` when requested end point is earlier than start point.
Use `return someFunction()` if return value is got from a single function. Lua can optimize this.
=> [fix] Improve performance of Database (strings)

Database/Corrections/Classic/classicItemFixes.lua
Fixes item [Stormwind Seasoning Herbs (2665)](https://classic.wowhead.com/item=2665/stormwind-seasoning-herbs)
- npcDrops [Felicia Gump (1303)](https://classic.wowhead.com/npc=1303/felicia-gump)
- relatedQuests [Seasoned Wolf Kabobs (90)](https://classic.wowhead.com/quest=90/seasoned-wolf-kabobs)
=> Fix item Stormwind Seasoning Herbs (2665)

Database/Corrections/Classic/classicItemFixes.lua
The item [Flagon of Dwarven Honeymead (2594)](https://classic.wowhead.com/item=2594/flagon-of-dwarven-honeymead) had an incorrect npc in its `npcDrops` list: [Mikhail (4963)](https://classic.wowhead.com/npc=4963/mikhail) does not sell that item. Now that `vendors` is used in quest objectives, I am fixing that in this PR. Also, the item was missing the `relatedQuests` [The Third Fleet (288)](https://classic.wowhead.com/quest=288/the-third-fleet).
=> Fix item Flagon of Dwarven Honeymead (2594)

Modules/QuestieValidateGameCache.lua
Fixing quite theoretical bug in validation of questlog cache during addon load process.
=> [fix] API can return nil if no quest data

Modules/Tracker/QuestieTracker.lua
Tracker quest item button gets hidden for `The Multiphase Survey` (11880) quest when equipping the item because it is a head piece. This PR checks all equipped slots for quest items instead of only trinkets and weapons.
=> [fix] Check all equipped slots for tracker items

Database/Corrections/Classic/classicItemFixes.lua, Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [Thunderbrew (117)](https://classic.wowhead.com/quest=117/thunderbrew) which name was incorrect. Also fixed related items to be from vendors rather than npcDrops.
One thing remains thought, the item [Keg of Thunderbrew (1262)](https://classic.wowhead.com/item=1262/keg-of-thunderbrew) is not an npcDrop from [Grimbooze Thunderbrew (239)](https://classic.wowhead.com/npc=239/grimbooze-thunderbrew), but instead a reward from the quest [Thunderbrew (117)](https://classic.wowhead.com/quest=117/thunderbrew). The question is, should that questId be added to the item `questRewards` field (if I understood the purpose), and do we still need the `npcDrops` hack then?
=> Fix quest Thunderbrew (117) and related items

Database/Corrections/Classic/classicNPCFixes.lua, Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [The Missing Diplomat (1267)](https://classic.wowhead.com/quest=1267/the-missing-diplomat) that was incorrectly set to start from Archmage Tervosh, but is in fact started and finished by [Lady Jaina Proudmoore (4968)](https://classic.wowhead.com/npc=4968/lady-jaina-proudmoore).
Also added Jaina's spawn nearby Tervosh after you turn-in quest [The Missing Diplomat (1324)](https://classic.wowhead.com/quest=1324/the-missing-diplomat).
=> Fix quest The Missing Diplomat (1267)

Database/Corrections/Classic/classicQuestFixes.lua
The location of quest [Investigate the Camp (201)](https://classic.wowhead.com/quest=201/investigate-the-camp) contained a wrong location in Westfall, but also the proper location in Stranglethorn Vale was slightly off; it was just a tad outside the camp, making the waypoint arrow points slightly on the side.
=> Fix quest Investigate the Camp (201)

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [The Tome of Nobility (4485)](https://classic.wowhead.com/quest=4485/the-tome-of-nobility) which is started by [Tiza Battleforge (6179)](https://classic.wowhead.com/npc=6179/tiza-battleforge) and not Arthur in SW.
FYI, the quest [The Tome of Nobility (1661)](https://classic.wowhead.com/quest=1661/the-tome-of-nobility) did not show up on the map for me, even thought I got a level 40 dwarf paladin that can pick it up. I looked into the DB and didn't see anything wrong, so perhaps something is odd within the code.
=> Fix quest The Tome of Nobility (4485)

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [Beginnings (1599)](https://classic.wowhead.com/quest=1599/beginnings) missing on the map. It was mistaken for quest 1559.
=> Fix quest Beginnings (1599)

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [Distracting Jarven (308)](https://classic.wowhead.com/quest=308/distracting-jarven) which actually does not require [Guarded Thunderbrew Barrel (403)](https://classic.wowhead.com/quest=403/guarded-thunderbrew-barrel) to be completed. 
Both these quests are actually child quests of [Bitter Rivals (310)](https://classic.wowhead.com/quest=310/bitter-rivals); they can only be done while you have that quest in your quest log. Once [Bitter Rivals (310)](https://classic.wowhead.com/quest=310/bitter-rivals) has been turned-in (when you pick up the barrel and take the follow-up quest), [Distracting Jarven (308)](https://classic.wowhead.com/quest=308/distracting-jarven) and [Guarded Thunderbrew Barrel (403)](https://classic.wowhead.com/quest=403/guarded-thunderbrew-barrel) both become …
=> Fix quest Distracting Jarven (308)

Database/Corrections/Classic/classicItemFixes.lua, Database/Corrections/Classic/classicObjectFixes.lua
Fix item [Heartswood (6912)](https://classic.wowhead.com/item=6912/heartswood) that is not an NPC drop, but actually a drop from the [Heartswood (93192)](https://classic.wowhead.com/object=93192/heartswood) object in Ashenvale. Also slight fix to Heartswood object coordinates to be more precise.
=> Fix item Heartswood (6912)

Database/Corrections/Classic/classicItemFixes.lua
To my surprise, I just got [Ring of Zoram (5445)](https://classic.wowhead.com/item=5445/ring-of-zoram) dropping for me by NPC [Lady Vespia (10559)](https://classic.wowhead.com/npc=10559/lady-vespia). Also added missing related quest [Ruuzel (1009)](https://classic.wowhead.com/quest=1009/ruuzel).
=> Fix item Ring of Zoram (5445)

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [Summon Felsteed (4490)](https://classic.wowhead.com/quest=4490/summon-felsteed) that requires one of the prequest to be completed before we can pick it up.
=> Fix quest Summon Felsteed (4490)

Database/Corrections/Classic/classicItemFixes.lua
Fix item [Lesser Invisibility Potion (3823)](https://classic.wowhead.com/item=3823/lesser-invisibility-potion) missing related quest [Liquid Stone (715)](https://classic.wowhead.com/quest=715/liquid-stone).
=> Fix item Lesser Invisibility Potion (3823)

Database/Corrections/Classic/classicItemFixes.lua
Fix item [Battered Junkbox (16882)](https://classic.wowhead.com/item=16882/battered-junkbox) causing stack overflow, because it contained itself.
=> Fix item Battered Junkbox (16882) causing stack overflow

Database/Corrections/Classic/classicItemFixes.lua
Fix item [Gyrochronatom (4389)](https://classic.wowhead.com/item=4389/gyrochronatom) missing just about all information about it.
=> Fix item Gyrochronatom (4389)

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [Fragments of the Orb of Orahil (1799)](https://classic.wowhead.com/quest=1799/fragments-of-the-orb-of-orahil) which requires one of the "Knowledge of the Orb of Orahil" prequest to be completed before it can be picked up.
=> Fix quest Fragments of the Orb of Orahil (1799)

Modules/Quest/QuestieQuest.lua
After a reload/login no tooltips on items/mobs are added for complete quests (still in quest log but ready to turn in).
Not sure if there is an open issue for this.
- Complete quests will now also register tooltips on mobs and items
- This is the same behaviour for when you complete a quest and don't do a reload
Taken after a /reload
=> [fix] Fix tooltips not registering for completed quests on mobs and items

Database/Corrections/Classic/classicNPCFixes.lua
Fix [Cursed Sycamore (5881)](https://classic.wowhead.com/npc=5881/cursed-sycamore) spawn location and add waypoints.
@BreakBB is there a quick hack to display waypoints for testing, other than having the quest active? Thanks
=> Fix spawn position and add waypoints for Cursed Sycamore (5881)

Database/compiler.lua, Modules/QuestieStream.lua, cli.lua
Add "raw_assert" mode to test overflows while writing into a raw stream.
This mode is active for DB compile while Questie debug mode is on.
Also:
* Kind of require defining decoding mode to QuestieStream.
* Check mode is correct when using recycled stream.
=> Test datatype overflows at DB compile while debug on.

Modules/QuestieStream.lua
Easy change, nothing major. There would be a lot more to gain.
Profiling testing:
Time consumed improves roughly from 4.6s to 4.1s without some yields. With those yields it consumes like 3.5s more. Not real time, but cpu time. Most likely yields mess profiling badly.
=> [fix] Improve Database compile performance (stream writing)

Database/compiler.lua, Modules/Quest/QuestieQuest.lua
I measured 8-10ms less cpu used by Questie once available Quests are populated. (488ms -> 477ms-480ms)
Also adds `return nil` after error prints. Without these code runs to lua error, which is catched.
Please merge so that every commit ends up as an individual commit to master.
=> Improve database performance, fix possible DB query error

Database/QuestieDB.lua
Faster to process in this order. `preQuestSingle` before `preQuestGroup`.
=> [fix] Improve populating map performance

Database/compiler.lua
Databases were saved in randomish id order into database string. This PR keeps ids in sorted order.
Sorted order hopefully keeps memoryaccess more prefetchable.
This seemt to cut about 10ms from Questie cpu usage during login and map population.
Most likely slight regression to database compile. I didn't try to measure.
=> [fix] Improve Database performance (sort ids)

Modules/QuestieEventHandler.lua, Modules/QuestieInit.lua, Modules/QuestieSlash.lua, Questie.lua
Removed unnecessary timer waiting savedvars.
Move init code to more correct modules.
Hopefully this made it more readable.
Order of init processing is not modified.
=> [fix] Remove unnecessary timer from questie init.

Modules/Quest/QuestieQuest.lua
Fixes #3464
`quest.SpecialObjectives` is first initialized in `QuestieDB:GetQuest( )` with static data.
Rest of data is more or less created in `QuestieQuest:PopulateQuestLogInfo( )`
`QuestieQuest:ClearAllNotes()` deletes whole SpecialObjectives table so static data gets never filled back.
Quest completed and abandoned won't delete whole table, only clear AlreadySpawned field of it, which is also done in `QuestieQuest:ClearAllNotes()`. So I would *assume* not-deleting the table won't have side effects.
=> [fix] Special objectives vanish at loading screen

Database/compiler.lua, Modules/Libs/QuestieSerializer.lua
The enableObjectLimit is present only in these places, so it is not accessed at all. Only set.
=> Remove unused field enableObjectLimit

Modules/Quest/QuestieQuest.lua
The used function:
https://github.com/Questie/Questie/blob/7ccac2be2d51bb8ef0863a995bb8923b04a1d5ab/Database/QuestieDB.lua#L316-L321
It is used in many places in code.
=> Use ready function. no point to inline.

Database/Corrections/Classic/classicQuestFixes.lua, Localization/Translations/ExtraObjectives/ClassicObjectives.lua
Added extra objectives to quest [Defenders of Darrowshire (5211)](https://classic.wowhead.com/quest=5211/defenders-of-darrowshire) so that the ghouls that need to be killed in order to free Darrowshire spirits do appear on the map.
=> Add extra objectives to quest Defenders of Darrowshire (5211)

Database/Corrections/Classic/classicItemFixes.lua
Fix item [Sturdy Junkbox (16884)](https://classic.wowhead.com/item=16884/sturdy-junkbox) causing stack overflow because it contained itself in itemDrops list.
Someone should really write a script to sanitize the database to find and fix all these 😄
=> Fix item Sturdy Junkbox (16884) causing stack overflow

Modules/QuestieValidateGameCache.lua
Current use of the "module" works fine, but future use cases may break without fix.
=> implement own tunpack into QuestieValidateGameCache

Modules/QuestieAnnounce.lua
Also satisfy "luacheck" false warning about itemId nil
in itemCache[itemId], which is not possible.
=> Add early return.

Modules/Tracker/QuestieTracker.lua
It is never called with an arguments
NOT TESTED
=> Refactor QuestiTracker:Toggle

Database/QuestXP/QuestieXP.lua, Database/QuestieDB.lua, Database/compiler.lua, Localization/l10n.lua, Modules/Auto/QuestieAuto.lua, Modules/FramePool/QuestieFramePool.lua, Modules/Journey/QuestieJourney.lua, Modules/Libs/QuestieLib.lua, Modules/Map/QuestieMap.lua, Modules/Map/QuestieMapUtils.lua, Modules/Network/QuestieComms.lua, Modules/Options/SocialTab/QuestieOptionsSocial.lua, Modules/Quest/QuestieQuest.lua, Modules/Quest/QuestieQuestPrivates.lua, Modules/QuestieAnnounce.lua, Modules/QuestieInit.lua, Modules/QuestieNameplate.lua, Modules/QuestieProfessions.lua, Modules/QuestieReputation.lua, Modules/QuestieSlash.lua, Modules/QuestieStream.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/Tooltips/Tooltip.lua, Modules/Tracker/QuestieQuestTimers.lua, Modules/Tracker/QuestieTracker.lua, Modules/Tracker/QuestieTrackerMenu.lua
Convert `x == nil` comparisons to `not x`, if `x` doesn't have different meanings for `nil` and `false`.
`(not x)` is more readable than `x == nil` most of time. As a bonus it is slightly faster (around 5%).
NOT REVIEWED. NOT TESTED.
=> [fix] Improve performance. Refactoring == nil

Database/Zones/zoneDB.lua, Database/compiler.lua, Modules/Journey/QuestieSearchResults.lua, Modules/Libs/QuestieLib.lua, Modules/Map/QuestieMap.lua
Can't use wow's unpack() as it stops at first nil value.
This is a bit band aid fix, but as bonus those querying only two fields
are faster when using QuerySingle twice.
**TEST BEFORE MERGE**
=> [fix] DB Query return value handling

Database/Corrections/Classic/classicItemFixes.lua
Fix item [Worn Junkbox (16883)](https://classic.wowhead.com/item=16883/worn-junkbox) causing stack overflows, because it contained itself in the list of itemDrops.
=> Fix item Worn Junkbox (16883) causing stack overflows

Database/Corrections/Classic/classicQuestFixes.lua
Fix quest [The Infernal Orb (1954)](https://classic.wowhead.com/quest=1954/the-infernal-orb), the quest [Return to the Marsh (1953)](https://classic.wowhead.com/quest=1953/return-to-the-marsh) is not required to pick up this quest, its only a breadcrumb.
=> Fix quest The Infernal Orb (1954)

Modules/QuestieValidateGameCache.lua
Seems timing is good enough on all users to run callbacks imediately
instead of via queue.
The bug stops Questie init fully, when timing is suitable.
=> fix callback queue to work

Modules/QuestieMenu.lua
- Adds [Aresella](https://www.wowhead.com/wotlk/npc=18991/aresella) as a First Aid profession trainer
=> Added Aresella (18991) to first aid profession

Database/Corrections/Wotlk/wotlkQuestFixes.lua
The quest item can only be used on the regular Stone Giants, not the Captive Stone Giants.
This fixes both the Horde and Alliance versions of this quest, which have the same bug.
=> [quest] Fix objective locations for "The Rune of Command"

Database/Corrections/Wotlk/wotlkNPCFixes.lua, Database/Corrections/Wotlk/wotlkQuestFixes.lua
Fixes #3811
Fixes #3812
Fixes #3822
Fixes #4194
Fixes #4195
Most of these are commented on in their individual commits.
This bundle of fixes should, from what I can tell, fix all objective issues with Horde quests in Howling Fjord.
=> Bundle of quest fixes

Database/Corrections/Wotlk/wotlkQuestFixes.lua
Fix quest [Catch and Release (9629)](https://www.wowhead.com/tbc/quest=9629/catch-and-release) missing extra objectives.
=> Fix quest Catch and Release (9629)

Modules/Map/QuestieMap.lua
Fixes https://github.com/Questie/Questie/issues/4213
- Adds a short delay before calculating the nearest objective, preventing an intermittent LUA error
N/A
=> Add small delay to GetNearestSpawn

Database/Corrections/Classic/classicQuestFixes.lua
Fix hunter taming quests locations; use objectives rather than triggers.
This has the following advantages:
- No need to specify the objective text
- A lot more locations now appear on the map, which is super useful when someone already tamed the npc where you expected to find it
- This in turn revealed many more locations which are much closer to the quest giver, such as the Strigid Screecher for Night Elf hunters
- In the future, if more locations are added/changed for these npcs, then they will automatically apply to the quest objectives
One thing is that the icons on the map will be a sword instead of a magnifying glass, which is no big deal imho.
=> Fix hunter taming quests

Modules/Quest/QuestEventHandler.lua, Modules/Quest/QuestieQuest.lua
Fixes #3525
Fixes #3452
Fixes #3713
Fixes #3714
- Reintroduce Comms messages for Quest acceptance and removal
=> Reintroduce Comms messages for Quest acceptance and removal

Database/Corrections/Classic/classicQuestFixes.lua
I never really paid attention to this before, but this morning I just saw that there's a quest when playing human in Dun Morogh that was available on an NPC which wasn't visible on map.
=> Fix quest Frostmane Hold (287) not appearing on map for humans

Database/Classic/classicQuestDB.lua, Database/Corrections/classicQuestFixes.lua, Database/Corrections/tbcQuestFixes.lua, Database/Corrections/wotlkQuestFixes.lua, Database/QuestieDB.lua, Database/TBC/tbcQuestDB.lua, Database/Wotlk/wotlkQuestDB.lua, Database/questDB.lua, Modules/QuestieProfessions.lua
This PR adds two DB parameters, `requiredSpell` and `requiredSpecialization`. It also adds a list of specializationKeys to QuestieProfessions.
`requiredSpell` means the quest will not show as available if the player lacks the spellID specified.
`requiredSpecialization` has some slightly complex logic. If fed a specializationKey (new), the quest will be hidden if the player does not have that specialization, checked with the basic `IsSpellKnown()` API call. If fed a professionKey, the quest will be hidden if the player either lacks that profession entirely, or has the profession *and* any of its specializations learned. In essence, this is a test to see if the player has *just* the base profession learned, and is therefore eligible to learn a specialization.
By default, all quests have …
=> Add requiredSpell and requiredSpecialization to quest database

Database/Corrections/classicItemFixes.lua, Database/Corrections/classicObjectFixes.lua
- Fix missing item [Unlit Torch (190307)](https://www.wowhead.com/classic/item=190307/unlit-torch)
- Fix [Wooden Figurine (375544)](https://www.wowhead.com/classic/object=375544/wooden-figurine) object ID and more precise location
=> Fix missing item Unlit Torch

Database/Corrections/classicQuestFixes.lua
Fix Paladin quest The Tome of Valor
- Quest [The Tome of Valor (1793)](https://www.wowhead.com/classic/quest=1793/the-tome-of-valor) is repeatable
- Quest [The Tome of Valor (1794)](https://www.wowhead.com/classic/quest=1794/the-tome-of-valor) is started by [Tiza Battleforge (6179)](https://www.wowhead.com/classic/npc=6179/tiza-battleforge) and is repeatable
=> Fix quest The Tome of Valor (1793, 1794)

Database/Corrections/QuestieQuestBlacklist.lua
Fix quest [The Tome of Nobility (1661)](https://www.wowhead.com/classic/quest=1661/the-tome-of-nobility) not showing up on the NPC in Classic Era. Quest was marked as hidden by Questie. I investigated and found that it was blacklisted. This is a mistake because this quest exists in Classic Era, and also exists in TBC and Wrath.
=> Fix quest The Tome of Nobility (1661)

.vscode/settings.json, Modules/QuestieDBMIntegration.lua
Fixes #4745
reported error with DBM Hud when enabled, causing errors related to changes with the quest icons
```
1x ...ace\AddOns\Questie\Modules\QuestieDBMIntegration.lua:28: attempt to index local 'icon' (a number value)
[string "@Interface\AddOns\Questie\Modules\QuestieDBMIntegration.lua"]:28: in function <...ace\AddOns\Questie\Modules\QuestieDBMIntegration.lua:25>
[string "@Interface\AddOns\Questie\Modules\QuestieDBMIntegration.lua"]:200: in function `RegisterHudQuestIcon'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:684: in function `DrawWorldIcon'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:631: in function `AddFinisher'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:473: in function `UpdateQuest'
[string …
```
=> Fix for DBM Hud issue

Database/Corrections/classicQuestFixes.lua
Fix quest [Morganth (249)](https://www.wowhead.com/classic/quest=249/morganth) ca also be started by npc [Theocritus (313)](https://www.wowhead.com/classic/npc=313/theocritus).
=> Fix quest Morganth (249)

Database/Corrections/classicItemFixes.lua
Fix item [Branch of Cenarius (5461)](https://www.wowhead.com/classic/item=5461/branch-of-cenarius) that can only be dropped by [Geltharis (4619)](https://www.wowhead.com/classic/npc=4619/geltharis), it is **not** dropped by [Prince Raze (10647)](https://www.wowhead.com/classic/npc=10647/prince-raze).
=> Fix item Branch of Cenarius (5461)

Database/Corrections/classicQuestFixes.lua
Got an error from Questie after picking up quest [Raene's Cleansing (1046)](https://www.wowhead.com/classic/quest=1046/raenes-cleansing).
```
Questie: [ERROR] Missing objective data for quest  1046   Dartol's Rod of Transformation
```
This quest has two item objectives, one was missing.
=> Fix quest Raene's Cleansing (1046)

Database/Corrections/classicQuestFixes.lua
Fix quest [Elmore's Task (1097)](https://www.wowhead.com/classic/quest=1097/elmores-task) missing [Verner Osgood (415)](https://www.wowhead.com/classic/npc=415/verner-osgood) as starter.
=> Fix quest Elmore's Task (1097)

Modules/Tracker/QuestieTracker.lua
Fixes #4781
Fixes #4781
- The Tracker again shows `0/1` and `1/1`for objectives with just one required objective amount
- This does NOT change/reintroduce it for Achievements
=> [fix] Fix Tracker not showing 0/1 and 1/1 objectives

Database/Corrections/classicQuestFixes.lua
Fix quest [Jonespyre's Request (3787)](https://www.wowhead.com/classic/quest=3787/jonespyres-request) and [Jonespyre's Request (3788)](https://www.wowhead.com/classic/quest=3788/jonespyres-request) not showing on map because the pre-req quest was wrong.
=> Fix quest Jonespyre's Request (3787, 3788) not visible on map

Database/Corrections/classicNPCFixes.lua
Fix npc [Arei (9598)](https://www.wowhead.com/classic/npc=9598/arei) location that was off by quite a few yards.
=> Fix npc Arei (9598)

Database/Corrections/classicQuestFixes.lua
Fix quest [Ironband's Compound (1681)](https://www.wowhead.com/classic/quest=1681/ironbands-compound) missing from map, because quest [Tormus Deepforge (1680)](https://www.wowhead.com/classic/quest=1680/tormus-deepforge) is just a breadcrumb and not a prequest.
Verified on classic era live server with a human warrior level 12 that was able to pick this up even thought he never completed quest 1679, 1678 or 1680.
=> Fix quest Ironband's Compound (1681)

Database/Corrections/classicQuestFixes.lua
Typos where made when setting `childQuests`.
`7769` is non existant. `7669` exists and is actually the child quest
=> Update `The Darkreaver Menace`

.luacheckrc, .vscode/settings.json, Localization/Translations/TrackerUI.lua, Modules/Tracker/TrackerMenu.lua
Fixes #4587 
- This static popup dialog box now closes after the player presses CTRL + C
- The message "Copied URL to clipboard" also appears on screen as confirmation
=> [feature] Add CTRL + C/auto close feature to WoWHead URL static popup

Localization/Translations/Options/Tracker.lua, Modules/Libs/QuestieLib.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/Options/TrackerTab/QuestieOptionsTracker.lua, Modules/Tracker/QuestieTracker.lua
Fixes #5000 
Several bug reports and comments on Discord.
- Added a new Objective Color option called **Minimalistic**. All Tracked Objectives will always be _White_ and will not show the "Blizzard Completion Text". Instead, it displays the old tags. Either "Quest Complete!" or "Quest Failed!".
- Based on user feedback we've changed the color of the "Blizzard Completion Text" to always be _Green_ in the _White_ Objective Color option.
- Updated the Tracker Default Objective Color option from **White** to **Minimalistic**. This will not change your settings in the next update. If the option isn't already set, usually new installs and new characters, then it'll set it to **Minimalistic**.
- Based on user feedback we've added a new toggle to Questie Config --> Tracker. "Hide Blizzard …
=> [feature] Add new Tracker Objective color option "Minimalistic"

Database/Corrections/classicQuestFixes.lua
Fixes #5063
Senir's observations part 2 becomes unavailable if you've already completed frost mane hold. Part 1 was already removed using the same method. This PR removes part 2.
=> Senir's observations part 2 becomes unavailable if you have completed frostmane hold

Modules/Quest/QuestieQuest.lua, Modules/Tooltips/Tooltip.lua
Fixes #5098
This is partly also related to #5092 as the finisher should then show on "Broken Barrel"
-
-
Starter:
Finisher:
=> [fix] Show quest starter/finisher on objects

Modules/FramePool/QuestieFrame.lua, Modules/Quest/QuestieQuest.lua, Modules/QuestieNameplate.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/Tooltips/Tooltip.lua
Fixes #5117
Hovering over an object:
Hovering over the map icon for that object:
=> [fix] Fix double complete map icon tooltip

Database/Corrections/classicItemFixes.lua, Database/Corrections/classicObjectFixes.lua, Database/Corrections/classicQuestFixes.lua, Database/Corrections/wotlkQuestFixes.lua, Localization/Translations/ExtraObjectives/ClassicObjectives.lua
Classic/TBC quests dont have objectives.
WOTLK quests do have objectives.
Renamed the 2 monuments so we can link the tooltips to them.
Fixed coords for the monuments, maps are identical across expansions.
Removed the "sourceitemid into requiredsourceitems" corrections, as that's plain wrong.
Removed object sources for the sourceitemid.
Classic corrections - added an extraobjective field for them, which is nil'ed in wotlk corrections.
Wotlk corrections now have objectives, linked to the monuments.
Tooltips should be visible on map and monuments in both era and wotlk.
Translations for the extraobjective definitions.
=> [quest] Fx quests of "Harvest Festival"

.luacheckrc, .vscode/settings.json, Modules/Compatibility.lua, Questie-Classic.toc
- Fix Questie tracker runtime exceptions, this enables clicking on the tracker and sub menus on 1.14 again
=> Add compatbility layer for 1.13 to 1.14

Localization/Translations/Zones/Raids.lua
Localization for `ptBR` and `ruRU` was mixed up with each other.
=> Fixed messed up ICC raid name translation

Modules/Network/QuestieComms.lua, Modules/QuestiePlayer.lua
Fixes #5165
- Add support for broadcasting when in an instance group, such as LFD.
I tested this in-game and it no longer shows the error mentioned in the above issue. I also confirmed that it is sharing data with other members of the instance group. I made it send as BULK in case BG messages are ever enabled.
=> Add support for comms in LFG/LFD.

Modules/QuestieEventHandler.lua
[Fix]  Faction changed event fixed on deDE by removing extra ' characters
It should not have any repercussions as the change is the same as zhCN and koKR does it.
=> [Fix]  Faction changed event fixed on deDE by removing extra ' characters

Database/Corrections/SeasonOfDiscovery.lua
added 8370 and 8171 to SoD blacklist as they aren't available till a later phase
Fixes #
-
-
=> [quest] Add 2 more quests to SoD blacklist

Modules/QuestieCoordinates.lua
- Sometimes the title text is nil, even when mapCoordinates is enabled and the world map frame is visible.
- This is the case when using addons such as GW2UI which probably does something funky.
#5299 
- Add a null check before attempting to call 'setText()' on the map title text object.
=> Ensure MapTitleText is valid

Database/Corrections/QuestieEvent.lua
Return false for darkmoonfaireactive when C_Calender is null
Fixes #
#5326 
always return false when C_Calender does not exist
-
-
No errors any more
=> Always return false when C_Calender does not exist for darkmoon faire

Database/Corrections/sodQuestFixes.lua
Fixes #
Warlock runes changed:
- Blizzard changed the price of "Demolition Explosives" for "Lake of Fire" rune to 1 gold from 5 gold
- Changes the "Incinerate" rune fake quest to an elite quest (because source is an elite mob + adds)
=> two warlock rune fixes

Database/Corrections/classicItemFixes.lua
Fixes #5375
- FIXED: Removed 'Lady Vespia' from npcDrops so that the mob path for 'Ruuzel' is now fixed.
=> [quest] FIXED: Removed 'Lady Vespia' From npcDrops for 'Ruuzel'

Database/Corrections/classicQuestFixes.lua
Fixes #
- The quest gives reputation with undercity not Orgrimmar, see also https://www.wowhead.com/classic/quest=518/the-crown-of-will
-
=> [quest] Fix reputation gain from "The Crown of Will"

Modules/Quest/QuestLogCache.lua, Modules/Quest/QuestieQuest.lua
Fixes #5078
- Remove the code-path for "number of objectives changed", because this only happens when the API returns invalid data after a teleport/loading screen and fixes itself soon after
- Restructured code-path to have less `if`s
- Remove reset of `quest.Objectives` on `SmoothReset` as that is fired after teleport and causes the Tracker to stop showing objectives for a short moment
=> [fix] Fix complete sound on teleport

Database/Corrections/tbcQuestFixes.lua, Database/Corrections/wotlkQuestFixes.lua, Database/questDB.lua
I noticed that the constant I used in my previous PR does not even exist. 
https://github.com/Questie/Questie/blob/master/Database/questDB.lua#L115
As the file where `factionIDs` are defined (right now only darkmoon) is not game-version specific, I wasn't sure if classic factions should be added there? I haven't played retail in a long time and I'm not sure if factions work the same through all versions?
So for now I reverted to the integer value for Undercity.
ref #5381
=> [bug] Add missing constant for undercity and replace more IDs with constants

Modules/Quest/QuestieQuest.lua
Fixes #5392
- On `QuestieQuest:ClearAllNotes` we need to reset `quest.Objectives.AlreadySpawned` for each objective
- That way the objective icons are redrawn on every `SmoothReset` while the Tracker does not lose the objectives
=> [fix] Fix objective icons not being redrawn after zone change

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5393
- ADDED: 'Trek Through the Caves' is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Trek Through the Caves' Rune Quest To QuestDB 

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #
-Adds "Second-Story Work" Night Elf Rogue quest related to Shadowstrike Rune.
-Also saw by coincidence that the other Shadowstrike Rune by mistake had the wrong spellobjective. 
Was Engrave Gloves - Crusader Strike (the paladin rune).
Is now Engrave Gloves - Shadowstrike.
Fixed in a separate commit
=> Add "Second Story Work" rogue quest (Shadowstrike rune)

Modules/Tooltips/MapIconTooltip.lua
Currently when a quest has no description the reputation reward when holding shift is not displayed.
For example a quest with a description:
Here is a quest without description:
and with the fix:
All Tooltips above are with holding SHIFT
View the diff without whitespace to see the actually changes.
=> [bug] Fix displaying of reputation in Tooltip for quests that do not have a description

Database/Corrections/sodQuestFixes.lua
Fixes #5420
- ADDED: 'The Horn of Xelthos' now has a zoneID so the subtitle should now show `Shadowfang Keep` instead of `Unknown Zone` in the tracker.
=> [quest] ADDED: 'The Horn of Xelthos' Now Has ZoneID Link

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5429 
- ADDED: 'Savage Roar' Westfall Fake Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Savage Roar' Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5425
- ADDED: 'Exorcist' Duskwood Fake Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Exorcist' Duskwood Fake Rune Quest To QuestDB

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5460 
Linked To #5443
- ADDED: 'Ice Lance' Elwynn Forest Mage Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Ice Lance' Elwynn Forest Mage Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodNPCFixes.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5446 
- ADDED: 'Sunfire' Teldrassil Druid Fake Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] MODIFIED: Druid's "Sunfire" rune locations

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodNPCFixes.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5465 
- ADDED: 'Lacerate' Westfall Druid Fake Rune Quest is now in the QuestDB, and is currently hidden due to too many icons being loaded if it is not.
=> [quest]  ADDED: 'Lacerate' Westfall Druid Fake Rune Quest To QuestDB

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5468
- ADDED: 'Friend of the Library' Mage Rune Quest is now in the QuestDB, and is now accessible to users.
- MODIFIED: Book quests for both Alliance and Horde to have a `finishedBy` set to nil, as we are replacing it with this quest.
=> [quest] ADDED: 'Friend of the Library' Mage Rune Quest To QuestDB

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5470
- ADDED: 'Ice Lance' Durotar Mage Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Ice Lance' Durotar Mage Rune Quest To QuestDB 

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5471
- ADDED: 'Ice Lance' Tirisfal Glades Mage Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Ice Lance' Tirisfal Glades Mage Rune Quest To QuestDB

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5472
- ADDED: 'Ice Lance' Dun Morogh Mage Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Ice Lance' Dun Morogh Mage Rune Quest

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5479
- ADDED: 'Void Plague' Elwynn Forest Priest Fake Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Void Plague' Elwynn Forest Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodNPCFixes.lua, Database/Corrections/sodQuestFixes.lua, Database/QuestieDB.lua
Fixes #5526
- ADDED: 'Beast Mastery' Silverpine Forest Hunter Fake Rune Quest is now in the QuestDB, and is currently hidden due to the bears spawn points in the quest scattered across the entire zone.
=> [quest] ADDED: 'Beast Mastery' Silverpine Forest Hunter Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5532
- ADDED: 'Shared Pain' Dun Morogh Priest Fake Rune Quest is now in the QuestDB, and should be accessible to users.
=> [quest] ADDED: 'Shared Pain' Dun Morogh Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5534
- ADDED: 'Shared Pain' Elwynn Forest Priest Fake Rune Quest is now in the QuestDB, and is currently hidden due to too many icons associated from the kobolds required.
=> [quest] ADDED: 'Shared Pain' Elwynn Forest Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5537
- ADDED: 'Shared Pain' Teldrassil Priest Fake Rune Quest is now in the QuestDB, and should now be accessible to users.
=> [quest] ADDED: 'Shared Pain' Teldrassil Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodNPCFixes.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5539 
- ADDED: 'Shared Pain' Durotar Priest Fake Rune Quest is now in the QuestDB, and should now be accessible to users.
=> [quest] ADDED: 'Shared Pain' Durotar Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5541 
- ADDED: 'Shared Pain' Tirisfal Glades Priest Fake Rune Quest is now in the QuestDB, and should now be accessible to users.
=> [quest] ADDED: 'Shared Pain' Tirisfal Glades Priest Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5557
- ADDED: 'Homunculi' Durotar Priest Fake Rune Quest is now in the QuestDB, and is currently hidden due to too many icons from the Voodoo Trolls.
=> [quest] ADDED: 'Homunculi' Durotar Priest Fake Rune Quest To QuestDB

Database/Corrections/classicQuestFixes.lua
The required reputation for Argent Dawn is neutral and not honored for this quest. The quest objective is still being honored, but the quest can be accepted already with neutral. Maybe even unfriendly, but I cannot find that out.
Screenshots attached that show the quest with my char being neutral.
=> Fix required reputation for quest "The Dread Citadel" to be neutral instead of honored

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5601
Linked To #5443
- ADDED: 'Lava Burst' Shaman Fake Rune Quest is now in the QuestDB, and is currently hidden due to Mudsnout Shaman spawns.
=> [quest] ADDED: 'Lava Burst' Shaman Fake Rune Quest To QuestDB

Database/Corrections/SeasonOfDiscovery.lua
Fixes #5666
- ADDED: 'Alliance Trauma' & 'Horde Trauma' First Aid 300 Quests To Blacklist For P2.
- MODIFIED: Bumped Current Phase Of SoD To 2.
=> [quest] Blacklisted First Aid Trauma Quests & Bumped Phase Number

Database/Corrections/sodQuestFixes.lua
Fixes #5688 
- REMOVED: 'Lurkmane' NPC from 'Explosive Shot' rune quest
=> [quest] Removed Lurkmane From Explosive Shot NPCs

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5693 
Linked To #5636 
- ADDED: 'Blood Surge' Warrior fake rune quests
=> [quest] Add Warrior's 'Blood Surge' rune

Modules/Options/GeneralTab/QuestieOptionsGeneral.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/QuestieCoordinates.lua
- Add an option to enable map coordinates on Mini World Map's title, similar to how it works currently on full sized World Map. 
- There is a small issue of "Show Mini World Map Coordinates" not fitting existing option structure, so I had to trim it manually to "Mini World Map Coord.".
- Map's original title shows up for a moment when changing zones and when you open a map after closing it with any other zone being selected that is not your current one. This is most likely because Blizzard UI changing title to match currently selected zone before WriteCoords has a chance to be run due to it having relatively low update interval. I don't think this is a major issue, but I understand if pull request will be rejected because of it.
=> [feature] Add option to enable coordinates on Mini World Map

Database/Corrections/QuestieQuestBlacklist.lua
- This hides the druid quest "Heeding the Call" in Cata as it has been removed: https://www.wowhead.com/cata/quest=5924/heeding-the-call
=> [quest] Hide "Heeding the Call" in Cataclysm

Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/cataQuestFixes.lua
- This fixes the exclusivity of the "Conscript of the Horde" quest. This quest can be picked up with either "Preserving the Barrens" or "Warchief's Command: Northern Barrens!", but not both. (the latter two are still exclusive to each other)
- Updates the breadcrumbs between these quests for the entire chain
- Removes an old quest that was previously referenced in the chain, but has been removed from Cata
Here's a screenshot where I have both of these in my quest log showing that this is possible!
=> [quest] Fix "Conscript of the Horde" exclusivity

Database/Corrections/sodQuestFixes.lua
N/a
- FIXED: 'Penance' Priest rune quest to now have a `exlusiveTo` attribute to stop quests showing when one in the group has been completed.
=> [quest] Fix 'Penance' Priest Rune Quest

Database/Corrections/QuestieQuestBlacklist.lua
- Remove several Goblin Starting Experience Quests not in game
https://www.wowhead.com/quest=24860/profitable-preservation
https://www.wowhead.com/quest=24935/body-and-soul
https://www.wowhead.com/quest=24936/body-and-soul
https://www.wowhead.com/quest=25124/brute-brutality
https://www.wowhead.com/quest=25225/oil-change
https://www.wowhead.com/quest=25231/southseas-scum
https://www.wowhead.com/quest=25902/your-first-totem
https://www.wowhead.com/quest=25903/its-hot-and-it-might-explode
=> [quest] Hide Unavailable Goblin Starter Quests in Cataclysm

Database/Corrections/cataQuestFixes.lua
- This adds "By Hook Or By Crook" as a prequest to "Grol'dom's Missing Kodo"  - this one was previously shown as available even though you can't start it until this prequest is completed
=> [quest] Fix "Grol'dom's Missing Kodo" prequest

Database/Corrections/cataNPCFixes.lua, Database/Corrections/cataQuestFixes.lua
Fixes #6018 
- This change updates quest 850 'Kolkar Leaders' to reflect correctly on the map with the change in quest giver starting in Cataclysm.  Removes quest from old quest giver 3389 'Regthar Deathgate'.  Quest starts/ends with new quest giver 34841 Telar Highstrider.
=> [quest] Fix 'Kolkar Leaders' duplicated on map

Database/Corrections/sodQuestFixes.lua
N/a
- FIXED: 'Crusader Strike' Paladin rune quest to now have a `exlusiveTo` attribute to stop quests showing when one in the group has been completed.
=> [quest] Fix 'Crusader Strike' Paladin Rune Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6030 
- Adds quest 12738 'A Cry for Vengeance!' as a pre-req for quest(s) 'A Special Surprise' 12739, 12742-12750, 28649-28650.
- **Note:** Quest 'A Special Surprise' is a quest in the Death Knight starter area which has 12 different race-specific versions of the same quest with different quest id's, so there are 12 fixes. Original quests already appear to have correct race requirements, but not the correct pre-req requirements, so **questKeys.requiredRaces** is not included.
=> [quest] Fix 'A Special Surprise' being shown on map before completion of pre-req

Database/Corrections/sodQuestFixes.lua
N/a
- FIXED: 'Ice Lance' Mage rune quest to now have a `exlusiveTo` attribute to stop quests showing when one in the group has been completed.
=> [quest] Fix 'Ice Lance' Mage Rune Quest

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6086 
- Blacklists quest 4451 (The Key To Freedom) because it is no longer available
=> [quest] Blacklist "The Key To Freedom" in Cataclysm Classic

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6105 
- Blacklist Quest 5541 (Ammo for Rumbleshot)
- Blacklist Quest 400 (Tools for Steelgrill)
- Blacklist Quest 415 (Rejold's New Brew)
- Blacklist Quest 287 (Frostmane Hold)
- Blacklist Quest 317 (Stocking Jetsteam)
- Blacklist Quest 310 (Bitter Rivals)
N/A
=> [quest] Blacklist several quests in Dun Morogh that are not available in Cataclysm

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6134
- Blacklist quest 637 (Sully Balloo's Letter) which is no longer available in Cataclysm
=> [quest] Blacklist "Sully Balloo's Letter" for Cataclysm

Database/Corrections/cataItemFixes.lua
Fixes #6137
- Add a fix to include all mobs that drop Deepmoss Venom Sac
=> [quest] Fix 'Deepmoss Venom Sac' Mob Drops

Database/Corrections/cataObjectFixes.lua
Fixes #6056
- Add a fix to spawn locations for Altar of Goc as part of the Showdown quest.
=> [quest] Fix 'Altar of Goc' Spawn Location

Database/Corrections/SeasonOfDiscovery.lua
Fixes #6103
- Add multiple LBRS quests to SoD blacklist. They may come back in the future, although they will most likely have new quest IDs.
=> [quest] Add Multiple LBRS Quests To Blacklist

Database/Corrections/sodQuestFixes.lua
Fixes #6002
- Add a fix to 'A Broken Ritual' & 'Zapper Fuel' quests to show correct zone in SoD.
=> [quest] Fix Multiple Sunken Temple Quests To Show Correct Zone

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6035
- Add a fix to Questie corrections for the 'Funky Fungi' quest to blacklist it in Cata.
=> [quest] Fix 'Funky Fungi' Unavailable In Cata

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #5991
- Add a fix to Questie corrections for the 'The Corrupter' quest to blacklist it in Cata.
=> [quest] Fix 'The Corrupter' Unavailable In Cata

Database/Corrections/cataQuestFixes.lua
Fixes #6127
- Add a fix to include triggerEnd for 'Kinelory Strikes' as done in 'Missing In Action' & 'Supplies to Auberdine'.
=> [quest] Fix 'Kinelory Strikes' triggerEnd

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6069
- Add a fix to Questie corrections for the 'Horn of  Nez'ra' quest to blacklist it in Cata.
=> [quest] Fix 'Horn of Nez'ra' Unavailable In Cata

Database/Corrections/cataQuestFixes.lua
Fixes #6173
- Add a fix to prerequisite quest for the 'An Introduction Is In Order' quest.
=> [quest] Fix 'An Introduction Is In Order' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6174
- Add a fix to prerequisite quest for the 'Cenarion Property' quest.
=> [quest] Fix 'Cenarion Property' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6183
- Add a fix to requiredRaces for the 'Ghost Walker Post' quest to only show for Horde characters.
=> [quest] Add 'Ghost Walker Post' Horde Only

Database/Corrections/cataItemFixes.lua
Fixes #6185
- Add a fix to startQuest for the 'Marudine Prisoner Manifest' item to override the autogenerated `itemStartFixes.lua` which is linking to an incorrect quest currently.
=> [quest] Fix 'Maraudine Prisoner Manifest' startQuest

Database/Corrections/cataQuestFixes.lua
Fix tags for the first Wetlands quest chain, starting with "The Stolen Keg" and ending at "Assault on Menethil Keep".
There are two breadcrumb quests for this chain: "Hero's Call: Wetlands!" and "Checking on the Boys".
- Properly assign breadcrumb quests "Hero's Call: Wetlands!" and "Checking on the Boys" for "The Stolen Keg"
- Remove _preQuestSingle_ from "The Stolen Keg"
- Add _nextInQuestChain_ to breadcrumb quests
- Add _nextInQuestChain_ tags for entire chain, up to "Assault on Menethil Keep"
- Remove _preQuestSingle_ from "Assault on Menethil Keep" since pre-quest seems to be another breadcrumb (could start that quest without having done any of the previous quests)
=> [Quest] Cata Classic - Fix The Stolen Keg quest chain

Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua, Modules/MinimapIcon.lua, Modules/QuestieMenu/QuestieMenu.lua, Modules/WorldMapButton/WorldMapButton.lua
re-clicking the minimap icon with left click closes the dropdown menu, and re-clicking the icon with right click in the worldmap will close the dropdown menu as well
Fixes #6180
-Left clicking the Questie minimap icon will close the dropdown menu if its open
-Right clicking the Questie icon in the world map window will close the dropdown menu if its open
-This feature will work in classic and SOD, I will need to update the library to get it working in CATA 
https://github.com/user-attachments/assets/033d18fa-1122-49b1-b7c5-e7b1672b8c6a
https://github.com/user-attachments/assets/187d3130-31e1-43a5-a228-cdb56b5ec72f
=> Feature: Re-click Questie icon to close dropdown menu

Database/Corrections/cataQuestFixes.lua
Fixes #6102
- Add a fix to include `triggerEnd` for 'The Ultrasafe Personnel Launcher' as done in 'Missing In Action' & 'Supplies to Auberdine'.
=> [quest] Fix 'The Ultrasafe Personnel Launcher' triggerEnd

Database/Corrections/cataQuestFixes.lua
Another Menethil Harbor quest fix, "Claws from the Deep" and "Reclaiming Goods" only become available after completing "When Life Gives You Crabs".
- Set _preQuestSingle_ for "Claws from the Deep" and "Reclaiming Goods"
=> [Quest] Cata Classic - Fix pre-quest requirement for Claws from the Deep and Reclaiming Goods

Database/Corrections/cataQuestFixes.lua
Add quest chain tags to Greenwarden's Grove quests and only make "For Peat's Sake" available after completing "Mired in Hatred".
- Set _nextQuestInChain_ for relevant quests
- Set _preQuestSingle_ for "For Peat's Sake"
- Change objective icon of "For Peat's Sake" from _SLAY_ to _INTERACT_
- The objective is to extinguish fires using an item from your inventory, _INTERACT_ seems more appropriate
=> [Quest] Cata Classic - Fix Greenwarden's Grove quests

Database/Corrections/cataQuestFixes.lua
Fix Swiftgear Station quests to become available at the right time and add quest chain tags.
- Set proper _nextQuestInChain_ for relevant quests
- Set "Dark Iron Trappers" and "Gnoll Escape" as _preQuestGroup_ quests for "Yorla Darksnare", both need to be completed before it becomes available
- Remove _preQuestSingle_ for "Dinosaur Crisis", its pre-quest "Swiftgear Station" is a breadcrumb quest
=> [Quest] Cata Classic - Fix Swiftgear Station quests

Database/Corrections/cataQuestFixes.lua
"Anvilmar the Hero" is an optional quest for "The Twilight's Hammer Revealed", even though the NPCs are right next to eachother.
- Remove _preQuestSingle_ from "The Twilight's Hammer Revealed"
- Set "The Twilight's Hammer Revealed" as _nextQuestInChain_ for "Anvilmar the Hero"
=> [Quest] Cata Classic - Remove pre-quest restriction from The Twilight's Hammer Revealed

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6207
- Add a fix to Questie corrections for multiple BFD quests to blacklist it in Cata.
=> [quest] Fix BFD Quests Unavailable In Cata

Database/Corrections/cataQuestFixes.lua
Fixes #6205
- Add `preQuestGroup` quests for the 'The Wilds of Feralas' quest.
- Add `exclusiveTo`  quests for the 'The Wilds of Feralas' quest.
=> [quest] Fix 'The Wilds of Feralas' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6202
- Add `preQuestGroup` to the 'Rock Lobstrock!'' quest.
=> [quest] Fix 'Rock Lobstrock!' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6189
- Add a fix to include `triggerEnd` for 'Get Me Out of Here!' as done in 'Goggle Boggle' & 'Death from Below'.
=> [quest] Fix 'Get Me Out of Here' triggerEnd

Database/Corrections/QuestieQuestBlacklist.lua
Fixes #6247 
- Blacklists "Failed Incursion" since it no longer exists in Cataclysm (https://www.wowhead.com/cata/quest=9876/failed-incursion)
=> [quest] Blacklist "Failed Incursion" in Cataclysm

Database/Corrections/cataQuestFixes.lua
Fixes #6244
- Add `preQuestSingle` to the 'Zukk'ash Infestation' quest.
=> [quest] Fix 'Zukk'ash Infestation' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6242
- Add a fix to include correct `objectives` for 'Forces of Nature: Faerie Dragons'
=> [quest] Add 'Forces of Nature: Faerie Dragons' Objectives

Database/Corrections/cataQuestFixes.lua
Fixes #6240
- Add `preQuestSingle` to the 'Return to Vestia' quest.
=> [quest] Add 'Return to Vestia' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua, Localization/Translations/ExtraObjectives/CataObjectives.lua
Fixes #6104
- Add a fix to include `triggerEnd` for 'Seize the Ambassador' as done in 'Goggle Boggle' & 'Death from Below'.
=> [quest] Fix 'Seize the Ambassador' triggerEnd

Database/Corrections/cataItemFixes.lua, Database/Corrections/cataQuestFixes.lua
Fix the Menethil Harbor quest chain starting with "The Third Fleet" and ending at "The Eye of Paleth".
- Add _nextQuestInChain_ for entire chain
- Fix _npcDrops_ ID on Intrepid Strongbox Key for "Lifting the Curse"
=> [Quest] Cata Classic - Fix The Third Fleet quest chain

Database/Corrections/cataQuestFixes.lua
Fixes #6297
- Add `preQuestSingle` to the 'High Priestess Jeklik' quest.
=> [quest] Fix pre quest for 'High Priestess Jeklik'

Database/Corrections/cataQuestFixes.lua
Fixes #6282 
Fixes #6292  
Fixes #6293 
- Added pre-quest requirement for Population Con-Troll
- Added pre-quest requirement for Cozzle's Plan
- Added pre-quest requirement for Venture Company Mining
=> [quest] Fix pre-quests STV (Cata)

Database/Corrections/cataQuestFixes.lua
Make "Do the Right Thing", "Angry Scrubbing Bubbles" and "Terrible Little Creatures" Horde only, since they're unavailable on Alliance.
- Set `requiredRaces` flag for "Do the Right Thing", "Angry Scrubbing Bubbles" and "Terrible Little Creatures" to `raceKeys.ALL_HORDE`
=> [Quest] Cata Classic - Flag some Hillsbrad Foothills quests as Horde only

Modules/QuestieInit.lua
When locales initialized on ADDON_LOADED event, QUESTIE_LOCALES_OVERRIDE variable is not set by localization addon, as it is not loaded yet.
- Move locale initialization to PLAYER_LOGIN stages. 
It may increase load time only if QUESTIE_LOCALES_OVERRIDE is set and l10n:InitializeLocaleOverride() is called, so seems like no impact for most users with that.
=> [fix] Custom localization initialization fix

Modules/Tooltips/Tooltip.lua
Make sure `GetTooltip` argument is a string before trying to call `sub` on it. Looks like it is due to interaction with Plater that is causing it. I always get this error whenever a hostile nameplate is shown. This fix fixes it by making sure that the argument is a string.
You could argue that Plater should be fixed as well, which might be true but Questie shouldn't break either if sent arguments it can't handle.
=> Fix for non-string calls to GetTooltip

Database/Corrections/cataQuestFixes.lua
Added 3 quests that make this quest unavailable.
Source: https://www.wowhead.com/cata/quest=24463/probing-into-ashenvale#comments:id=1644184
Fixes #6476
=> [quest] 24463 Probing into Ashenvale

Database/Corrections/cataQuestFixes.lua
Add 3 prerequisite quests that all need to be completed before.
Alliance version still needs to be done.
See here: https://github.com/Questie/Questie/issues/6490
=> [quest] Add 25533 Pirate Accuracy Increasing

Database/Corrections/cataQuestFixes.lua
Also delete the wrong exclusiveTo quests
Fixes #6495
=> [quest] Filling Our Pockets - correct prerequisite quests

Database/Corrections/cataQuestFixes.lua
Old name: Damsels Were Made to be Saved
Translations look fine already
Fixes #6506
=> [quest] Town Dwellers Were Made to be Saved - fixed name

Database/Corrections/cataQuestFixes.lua
Made the former prerequisiste quest a breadcrumb quest instead.
Fixes #6507
=> [quest] Roll the Bones - removed unnecessary prequest

Database/Corrections/QuestieNPCBlacklist.lua, Database/Corrections/cataItemFixes.lua
Amulet of Allistarj drops from https://www.wowhead.com/cata/object=203229/allistarjian-vault now.
Amulet of Grol drops from https://www.wowhead.com/cata/npc=41267/spirit-of-grol instead of https://www.wowhead.com/cata/npc=7665/grol-the-destroyer
=> [db] Amulet of Allistarj / Grol - fix drop issues

Localization/Translations/Options/Sounds.lua, Modules/Options/GeneralTab/QuestieOptionsGeneral.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/Sounds.lua
Currently, most quest sounds (objective progress, objective completion) are played with a delay of 0.5 seconds after the actual event. This delay does not feel great for short progress sounds which play noticeably after the on-screen message appears.
This PR adds an option slider to configure a custom delay time for quest sounds. Default is 0.5, as before.
=> Add option to change delay before quest sounds

.luacheckrc, .vscode/settings.json, Modules/QuestieNameplate.lua
Support target frame from XPerl addon (https://github.com/Resike/Z-Perl, https://www.curseforge.com/wow/addons/zperl) for Target Frame Icon option.
=> Support XPerl Target for Target Frame Icon.

.luacheckrc, Localization/Translations/Options/Tracker.lua, Modules/EventHandler/EventHandler.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/Options/TrackerTab/QuestieOptionsTracker.lua
Fixes #7035
- When a user enters a pet battle, the tracker will now be hidden by default as this overlaps UI elements, and is unnecessary to show while in a pet battle.
=> [feature] Add hiding quest tracker during pet battles
