Questie/Questie.lua
=> Fix map/tracking behavior

Questie/Database/items.lua
See quest description http://db.vanillagaming.org/?quest=896
=> Fixed quest Miner's Fortune

!Questie/astrolabe/Astrolabe.lua
=> Adding Squeenix & simpleMiniMap Square Map support

!Questie/Modules/QuestieNotes.lua, !Questie/Modules/QuestieQuest.lua, !Questie/Questie.lua
Fixed;
- Some repeatable lines in tooltips, 
- Not showing info for some quest items. 
- Not showing info from 2 or more quest on mob tooltips. 
Improved performance
=> Fixed tooltips

!Questie/Questie.lua, !Questie/astrolabe/Astrolabe.lua
=> Fix icon position at minimap in city

!Questie/Modules/QuestieNotes.lua, !Questie/Questie.lua
=> Fix for #270

!Questie/Modules/QuestieNotes.lua
=> QuestieTBC: Fix debug printing (followup to #521)

!Questie/astrolabe/Astrolabe.lua
- bumped version to 19 (here is 17, TomTom Vanilla has 18)
- removed unecesssary condition in function Astrolabe:GetCurrentPlayerPosition()
- update timer reset in function Astrolabe:PlaceIconOnMinimap(...) in order to prevent excessive updating of minimap icons
- fixed issue that Astrolabe.ContinentList[continent][zone].mapName was always nil
- reduce rate of memory consumption (clearing arrays, removed unpack() - by Road-block, see https://github.com/cralor/TomTomVanilla/commit/b76ae2c9da1564ffe3218ef611ff8c315833f03f)
=> Astrolabe, issue #522

Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua, Libs/LibDBIcon-1.0/lib.xml, Questie.lua, embeds.xml
In reading through the AceLib stuff, found a minimap icon library.  Created the minimap icon to toggle the config window.  Currently does not have right-click features for enabling / disabling questie like the 1.12 version has.
=> Added minimap icon

Modules/QuestieCoordinates.lua, Questie.lua, QuestieDev-master-retail.toc, QuestieDev-master.toc
Added in a quick coordinate system. Configurable from config. Works on Map and minimap (and includes cursor and player position on map).  And snuck in a QoL access to instant quest text CVar (since it's quest related).
=> Coordinate System

Locale/en/config.lua, Locale/en/locale.xml, Locale/enUS/config.lua, Locale/es/config.lua, Locale/es/locale.xml, Modules/QuestieJourney.lua, Questie.lua
Fixed Type-o in function name
Added Minimap toggle slash command: /questie minimap
Added dungeon quests (that start *INSIDE* a dungeon, not all quests for that dungeon. This also fixed NPC searches for mobs located inside dungeons
Now clicking on a quest name inside of the "Also Starts / Also Finishes" areas will bring you to the search for that quest and auto-select that quest for you.
=> Updates to Journey System

README.md
For people reaching out to the Github repo!
=> Add installation guide link to readme

Database/corrections.lua
There are a lot of different breadcrumb quests for "The Tome of Divinity" which are added to the corrections with this PR.
=> Add possible fix for #703

Database/corrections.lua
Deleted the branch in mistake, but here is the fix once again.
=> Fix #712 (again)

Locale/frFR/config.lua
=> Fix config.lua

Database/graves.lua
`=` instead of `-` for unknown faction
=> Fix description in comment

Database/corrections.lua
reference - https://wow.gamepedia.com/Seasoned_Wolf_Kabobs
=> mark quest "[90] Seasoned Wolf Kobabs"  as a cooking quest

Questie.lua
eg: 
- Minimap Button Frame
- SexyMap
- ...
#1540
=> [#1540] Solve the problem that other addons could not find Questie minimap icon

Database/Corrections/QuestieQuestFixes.lua
Fixes breadcrumb quest (#1594)
=> [quest] Neeka Bloodscar

Database/Corrections/QuestieQuestFixes.lua
https://github.com/AeroScripts/QuestieDev/issues/1667
=> Update for #1667

Database/Corrections/QuestieQuestFixes.lua
=> Fix parent quest for quest 254

Database/Corrections/QuestieItemFixes.lua
=> Fix for #1810

Database/Corrections/QuestieItemFixes.lua
https://github.com/AeroScripts/QuestieDev/issues/1807
=> Correct fix for #1807

Database/Corrections/QuestieItemFixes.lua
=> Fix for "Mazrzanache"

Database/Corrections/QuestieItemFixes.lua
=> Fix for "Catch of the Day"

Database/Corrections/QuestieQuestFixes.lua
Fixes for #1950.
Hey @BreakBB , can you please add a thank you line in the release notes around this?
"Thanks to Qballs, Lawle, Firehot, and Cataclysms"
=> [quest] Issue around [60] The Call to Command & [60] Ramstein | Thanks to Qballs, Lawle, Firehot, and Cataclysms

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Issue around [1] Your Place In The World & [1] Cutting Teeth 

Database/Corrections/QuestieItemFixes.lua
=> [quest] Fixes for [44] Fool's Stout & [44] Zanzil's Secret | Thanks Aevala!

Database/Corrections/QuestieNPCFixes.lua
He moves around a little bit through town.
* Sage Korolusk - NPC - World of Warcraft || https://classic.wowhead.com/npc=14373/sage-korolusk
=> Giving Sage Korolusk a little pat

Database/Corrections/QuestieQuestFixes.lua
https://github.com/AeroScripts/QuestieDev/issues/2012
Cleaning up formatting, but I don't think this will help it.
=> [quest] Fixes for [60] The Truth Comes Crashing Down

Database/Corrections/QuestieQuestFixes.lua
Adding exclusivity.
ALLIANCE
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1015/the-new-frontier
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1019/the-new-frontier
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1047/the-new-frontier
HORDE
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1000/the-new-frontier
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1004/the-new-frontier
* The New Frontier - Quest - World of Warcraft || https://classic.wowhead.com/quest=1018/the-new-frontier
=> [quest] Fixes for Thew New Frontier

Database/Corrections/QuestieQuestFixes.lua
* Cenarion Battlegear - Quest - World of Warcraft || https://classic.wowhead.com/quest=8800/cenarion-battlegear
@drejjmit - Fixed!
=> [quest] Fixes for "Cenarion Battlegear" series

Modules/Auto/DisallowedIDs.lua
=> [quest] Add "Essence Mangoes" to disallowedQuests for autoaccept

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed start object of "Midsummer Stealing Flame" quests

Modules/Auto/DisallowedIDs.lua
=> Phase 5 DisallowedIDs for QuestieAuto

Database/Corrections/QuestieNPCFixes.lua
https://github.com/AeroScripts/QuestieDev/issues/2046#issuecomment-647117054
=> [quest] Fixed faction for "Midsummer Fire Festival" NPCs

Database/Corrections/QuestieQuestFixes.lua
https://discordapp.com/channels/263036731165638656/579966856085897216/725368670607507456
=> [quest] Fixed pre quest for "Kharan's Tale"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Tran'rek" as exclusive to "Scarab Shells"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Tinkmaster Overspark" as exclusive to "Save Techbot's Brain!"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Stonegear's Search" as exclusive to "Search for Incendicite"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Ironband Wants You!" as exclusive to "Find Agmond"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "I Know A Guy..." and "To Gadgetzan You Go!" as exclusive to "Clamlette Surprise"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "The Brassbolts Brothers" as exclusive to "Gahz'rilla"

Database/Corrections/QuestieQuestFixes.lua
Shows up as available in Journey if we have this here.
=> Fix for Liquid Stone

Database/Corrections/QuestieQuestFixes.lua
=> Wrong object ID.

Database/Corrections/QuestieNPCFixes.lua
Confirmed by ~20 people on wowhead
https://classic.wowhead.com/npc=5477/noboru-the-cudgel#comments:id=3159709
(won't tag it [quest] since we already have Noboru the Cudgel in change log)
=> Fix for Noboru the Cudgel

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fix pre quests of "The Brokering of Peace"

Database/Corrections/QuestieNPCFixes.lua
=> [db] Updated spawns of "Rot Hide Brute"

Database/Corrections/QuestieNPCFixes.lua
Will move her out of "Camp Taurajo" and on to the road where she paths. Also: 
https://classic.wowhead.com/npc=5797/aean-swiftriver#comments:id=2825660
=> [db] Fixed spawn of "Aean Swiftriver"

Modules/Auto/DisallowedIDs.lua
Darkmoon Faire Ticket Redemption
=> [quest] Added "Gelvas Grimegate" to disallowedNPC for autoaccept

Database/Corrections/QuestieItemFixes.lua
Removed Rare mobs that were not even close to rest of the npcs that drop this quest item.
=> [db] Fixed NPC drops for "Singing Blue Crystal"

Database/Corrections/QuestieItemFixes.lua
=> [db] Added missing item "Dawn's Gambit"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed pickup location of "Hunter's Path"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Report to Captain Stoutfist" as breadcrumb quest

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Updated objective locations for "Empty Stables"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed starting NPCs of "Report to Gryan Stoutmantle"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Updated objective locations for "Waking Legends"

Database/Corrections/QuestieQuestFixes.lua
Started by choosing gossip "May I have it, please." which will lead to getting [Elegant Letter] that starts this quest.
=> [quest] Fixed starting NPCs of "The Manor, Ravenholdt"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Flawed Power Stone" as exclusive to "The Demon Seed"

Database/Corrections/QuestieQuestFixes.lua
https://discordapp.com/channels/263036731165638656/263036731165638656/736343647569838180
=> [quest] Marked "The Hammer May Fall" as exclusive to "Call to Arms"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed starting NPCs of "Report to Anastasia"

Database/Corrections/QuestieItemFixes.lua, Database/Corrections/QuestieQuestFixes.lua
=> [db] Fixed sources of "Corrupted Felwood Sample"

Database/Corrections/QuestieNPCFixes.lua
=> [db] Fixed spawn of "Celebras the Redeemed"

Database/Corrections/QuestieQuestBlacklist.lua
=> [db] Blacklisted duplicate version of "The Captain's Cutlass/Chest"

Database/Corrections/QuestieObjectFixes.lua
Prevents error on [[60] Bang a Gong! (8743)]
=> [db] Updated location of "The Scarab Gong"

Database/Corrections/QuestieNPCFixes.lua
Will fix error on [[60] Mea Culpa, Lord Valthalak (8995)]
=> [db] Fixed spawn of "Spirit of Lord Valthalak"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed requirements of WPL Cauldron quests

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Fixed level requirement for "Dearest Natalia"

Database/Corrections/QuestieQuestFixes.lua
=> [quest] Marked "Speak with Deino" as breadcrumb quest

Database/Corrections/QuestieItemBlacklist.lua
=> [db] Blacklisted Dungeon Set 1 zone drops

Modules/Options/QuestieOptionsDefaults.lua
Since most servers are done with war effort.
=> [fix] Default option for "War Effort" is now off

Database/Corrections/QuestieItemFixes.lua, Database/Corrections/QuestieNPCFixes.lua
=> [db] Fix NPC drop for "Silver Totem of Aquementas"

Database/Corrections/QuestieQuestBlacklist.lua
This version from Lanka Farshot doesn't seem to be in the game.
#1957
=> [db] Blacklist unavailable version of "The Hunter's Path"

Database/Corrections/QuestieItemFixes.lua
=> [db] Fix NPC drops for "Merged Ooze Sample"

Database/Corrections/QuestieItemFixes.lua
https://github.com/AeroScripts/QuestieDev/issues/2348
=> [quest] Fix NPC drops for "Bloodkelp"

Database/Corrections/QuestieItemFixes.lua, Database/Corrections/QuestieQuestFixes.lua
=> [db] Add spawns for "Draconic for Dummies"

Database/Corrections/QuestieNPCFixes.lua, Database/Corrections/QuestieQuestFixes.lua
Fix: https://discordapp.com/channels/263036731165638656/579966856085897216/773084429161594881
=> [db] Fix pickup location of "Parts of the Swarm"

Database/Corrections/QuestieItemBlacklist.lua
https://github.com/Questie/Questie/issues/2534
=> Removal of P6 Farming Quests & Naxx Attune

Database/Corrections/QuestieItemFixes.lua
https://github.com/Questie/Questie/issues/2551
=> fix: The Black Shield - Acidic Venom Sac drops

Database/Corrections/QuestieItemFixes.lua
https://github.com/Questie/Questie/issues/2539
=> The Videre Elixir

Database/Corrections/QuestieQuestFixes.lua
https://github.com/Questie/Questie/issues/2489
=> Feathermoon Stronghold Quest Start Corrections

Database/Corrections/QuestieNPCFixes.lua
https://github.com/Questie/Questie/issues/2537
=> Fixes for Elder Riversong locaiton

Database/Corrections/QuestieQuestFixes.lua
https://github.com/Questie/Questie/issues/2492
=> Ironband's Excavation Breadcrumb Fix

Database/Corrections/QuestieQuestFixes.lua
https://github.com/Questie/Questie/issues/2516
=> Rabine Saturna Prereq Correction

Database/Corrections/QuestieQuestFixes.lua
Fixes for https://classic.wowhead.com/quest=6762/rabine-saturna (Alliance Quest)
=> rabine-saturna - Alliance Version

Database/Corrections/QuestieItemFixes.lua
https://github.com/Questie/Questie/issues/2570
=> Fixes for [39] Indurium

Modules/FramePool/QuestieFramePool.lua
resolves https://github.com/Questie/Questie/issues/1093
Adds text wrapping for quest details. See issue for example images.
=> feat: wrap quest details text in map tooltip

Database/Corrections/QuestieQuestFixes.lua
https://github.com/Questie/Questie/issues/2580
=> Fixes for [48] Stalking the Stalkers

Modules/Libs/QuestieCombatQueue.lua, Modules/Tracker/QuestieQuestTimers.lua, Modules/Tracker/QuestieTracker.lua
Fixes #2592
This also fixed that the Tracker does not show objectives on times quest.
=> [fix] Fix lagging when leaving combat while on a timed quest

Localization/Translations/DebugMessages.lua, Localization/Translations/Generics.lua, Localization/Translations/KeyboardShortcuts.lua, Localization/Translations/Map.lua, Localization/Translations/Professions.lua
Let me know if we I should use a different kind of pattern for commits messages.
Once this is merged I'll create a new one with more updates.
=> [locale][ptBR] Update translations

Localization/Translations/Journey/MyJourney.lua, Localization/Translations/Journey/QuestsByZone.lua, Localization/Translations/Journey/Search.lua, Localization/Translations/QuestStates.lua, Localization/Translations/TooltipsUI.lua, Localization/Translations/TrackerUI.lua
A few more translations added and also fixed a few others.
=> [locale][ptBR] Update more translations

Localization/Translations/Options/Advanced.lua, Localization/Translations/Options/DBMHud.lua, Localization/Translations/Options/General.lua, Localization/Translations/Options/Tracker.lua
=> [locale] Add more frFr translations

Localization/Translations/KeyboardShortcuts.lua
Keyboard button names leaved as is.
=> Update KeyboardShortcuts.lua ruRU translation

Localization/Translations/DebugMessages.lua
- Added german translation for the move to BC message
=> Update Move to BC Message

Modules/FramePool/QuestieFrame.lua, Modules/FramePool/QuestieFramePool.lua, Modules/Map/QuestieMapUtils.lua, Modules/Quest/QuestieQuest.lua
=> [fix] Fix "Hide Questie" to also hide waypoint lines

Database/QuestieDB.lua, Modules/QuestieProfiler.lua, Modules/Tracker/QuestieTrackerPrivates.lua
@BreakBB Your commits had almost all mine and a lot of more others.
These are stylish things that I had in addition.
=> Minor stylish fixes

Database/compiler.lua, Modules/Libs/QuestieLib.lua, Modules/Map/QuestieMap.lua
Some major and minor performance tweaks
=> Performance tweaks

Modules/Libs/QuestieLib.lua, Questie.lua
=> Remove deprecated addon version checks

Modules/Libs/QuestieLib.lua, Modules/Quest/QuestieQuest.lua
IMHO these are worth to backport to master for a p2 release.
1st commit fixes a bug when player has collapsed entries in quest log.
2nd commit removes unnecessary looping on heavy stuff. It could be improved a lot as even Levenshtein calculation can be left out. No such changes now as we want avoid new bugs.
=> [fix] backport fixes from event refactoring development

Database/QuestieDB.lua, Database/Zones/zoneDB.lua, Localization/l10n.lua
Add annotations for fields defined in other files
Remove one empty line to get automatical annotations from fields defined in code in same file.
=> Add annotations for few classes

Database/Corrections/Classic/classicQuestFixes.lua, Database/Corrections/TBC/tbcQuestFixes.lua, Database/QuestieDB.lua, Modules/Journey/tabs/QuestsByZone/QuestsByZone.lua, Modules/Libs/QuestieLib.lua, Modules/Quest/QuestieQuest.lua, Modules/QuestieEventHandler.lua, Modules/Tooltips/MapIconTooltip.lua
=> General cleanups

Modules/QuestLinks/ChatFilter.lua
Fixes #3146
And already closed (duplicate) issues:
Fixes #2821
Fixes #3024
Fixes #3036
Fixes #3054
offtopic rant: Why GitHub can't handle comma separated issues properly. Handles just halfly correctly
=> [fix] Check chatlink's questId exists in DB

Modules/Tracker/QuestieTracker.lua
=> [fix] Use Correct api function to get max number of quests in quest log

Modules/Tracker/QuestieTracker.lua
[fix] Handle gracefully zoneOrSort == 0
Fixes #3222 lua error
=> [fix] Handle gracefully zoneOrSort == 0.

Database/Corrections/QuestieEvent.lua, Database/Corrections/QuestieQuestBlacklist.lua, Database/QuestieDB.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/VersionCheck.lua
DMF is disabled on TBC and SoM.
Some code added for future quest XP from Elite/Dungeon Quests,
but the currently commented out
=> Add Questie.IsEra .IsSoM ; Enable DMF only on Era

Modules/Tracker/QuestieTrackerPrivates.lua
=> Dirty Fix for trying to move tracker in combat

Modules/Quest/QuestieQuest.lua, Modules/QuestieReputation.lua
Includes also few almost unrelated changes to call with (true) where function return values are not needed.
@BreakBB  Please merge also to #3111
=> Fix reputation standing to detect also a new faction

Modules/Quest/QuestEventHandler.lua
Ready to merge as is.
No big changes; changes:
* more debug
* more robust logic
* force game fill its cache faster
Still things todo.
=> quest-event-refactor-pr5

Database/QuestieDB.lua
Fixes #3142
Not yet tested on master branch.
=> [fix] Showing creature levels in map tooltips

Modules/Tracker/QuestieTracker.lua
=> [fix] Show Tracker even without any quest tracked

Database/Zones/zoneDB.lua, Modules/QuestieStream.lua
Cherry picked easy to validate changes from #3336
First commit is just localing global function.
2nd commit don't query data from DB before it is really needed. As most of cases it won't need it. Resulting massive performance improvement.
=> Reduce lag spike at login

Localization/l10n.lua
l10n.PostBoot 1 call 24ms -> 21ms
=> [fix] Reduce lag spike at login

Modules/Libs/QuestieLib.lua
Use similar logic for objectives cached/correctness checking as
in quest-event-refactor branch. I.e. remove use of levenshtein and
do it much faster.
QuestieLib.GetQuestObjectives() 121 calls 100ms -> 51ms
This reduces frametime spikes a lot when doing anything quest related because
code way too often runs the function tens of times in single frame.
=> [fix] Reduce lag spike at quest progress changes and at login

Database/Corrections/TBC/tbcQuestFixes.lua
=> [quest] Set correct levels to Lunar Festival quests on TBC

Database/Corrections/Classic/classicNPCFixes.lua, Database/Corrections/QuestieNPCBlacklist.lua, Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/TBC/tbcNPCFixes.lua, Database/Zones/zoneTables.lua
=> [database] Add spawns to many quest starting/end NPCs

Localization/Translations/DebugMessages.lua, Localization/Translations/Options/General.lua
=> [locale][ruRU] Update translations

Database/QuestieDB.lua, Modules/Quest/QuestieQuest.lua, Modules/Tooltips/MapIconTooltip.lua
On my lvl 70 toon about from 30MB to 28.4MB.
And around 5k less functions created.
There are still few to move outside.
=> [fix] Improve performance and memory usage

Modules/Map/QuestieMap.lua
[fix] Minimap markers fade stopping. Users don't see markers or markers from far away stay visible at minimap edge
=> [fix] Minimap markers fade stopping. Users don't see markers or markers from far away stay visible at minimap edge

Modules/Quest/QuestieQuest.lua
[fix] Check npc exists before registering tooltip
=> [fix] Check npc exists before registering tooltip

Database/QuestieDB.lua
=> [fix] Fix regression: Show quests without objectives as complete.

Modules/Quest/QuestieQuest.lua
Don't create new function at every function call.
=> [fix] Improve map popualting performance

Modules/QuestiePlayer.lua
=> Improve performance: get rid of a bit.band

.luacheckrc, Modules/Migration.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/Options/TrackerTab/QuestieOptionsTracker.lua, Modules/QuestiePlayer.lua, Modules/Tracker/QuestieQuestTimers.lua, Modules/Tracker/QuestieTracker.lua, Modules/Tracker/QuestieTrackerMenu.lua, Modules/Tracker/QuestieTrackerUtils.lua
=> Fix the Questie Tracker for Wotlk

Database/QuestieDB.lua
`if (x == nil) and x then` WTF? 
NOT TESTED.
=> [fix] Improve performance. Remove never true if block

Modules/Tracker/QuestieTracker.lua
=> Remove never used _QuestieTracker.trackerLineWidth

Database/Zones/zoneDB.lua
Cherry-picks from #3844 to make it smaller.
=> Improve performance of ZoneDB's Get zone/map/areaId functions

Database/Zones/zoneDB.lua, Database/Zones/zoneTables.lua
Cherry-pick from #3844 to make it smaller.
=> Improve performance, readability. Remove capsulating into a table

Modules/FramePool/QuestieFrame.lua
- in worldmap ctrl + left-click can now remove old waypoint when clicked second time
=> Better TomTom integration

README.md
Modified the readme.md since i got trouble for my first contribution finding a "nil" value in the translation-files, ther were only "false" when no translation exists.
if this is wrong, could someone explain if i am missing a point here. thanks :)
=> Correct readme.md

Database/Corrections/TBC/tbcQuestFixes.lua, Database/Corrections/Wotlk/wotlkQuestFixes.lua, Database/compiler.lua
Totally untested blindy coded.
Mentioning #3940
=> support multiple killobjectives in compiler

Modules/Tracker/ActiveQuestsHeader.lua, Modules/Tracker/QuestieTracker.lua, Modules/Tracker/QuestieTrackerPrivates.lua
Fixes #3988
Fixes #3986
Fixes #3997
=> Tracker fixes

.github/workflows/ci.yml, Modules/Tracker/QuestieTracker.lua
=> [fix] Fix collapsing of the Tracker

Modules/QuestieEventHandler.lua
=> [fix] Hopefully making it so that FACTION_STANDING_CHANGED logic doesn't crash the addon, could still be faulty

Database/Corrections/Wotlk/wotlkQuestFixes.lua
=> [quest] Fix objective locations for "Seeds of the Blacksouled Keepers"

Localization/Translations/Options/Tooltips.lua
- French traduction for new option (837d162548800c0625b87e078f497eaee6fe43a3)
=> XP at max level french traduction

Localization/Translations/ExtraObjectives/ClassicObjectives.lua
- Added several translations for ClassicObjectives
=> Added several translations for ClassicObjectives

Localization/Translations/Options/Tooltips.lua
Remove "m" in "maxmimum" word.
- Spelling fix from my previous pull request #4269
=> Spelling fix

Database/Corrections/QuestieCorrections.lua, Database/Corrections/TBC/tbcQuestFixes.lua, Database/Corrections/Wotlk/wotlkQuestFixes.lua, Database/QuestieDB.lua
Code change to make the killcredit objective ordering hopefully more stable and dynamic
=> Code to place killCredit at the first index

Database/Zones/zoneDB.lua, Database/Zones/zoneTables.lua, Modules/Journey/tabs/QuestsByZone/QuestsByZoneTab.lua
First try and fetch it from our table, afterwards we try to map it using a AreaName == UiMapIdName check
Tests added as well.
=> Fix/get area id by UI map

Database/Corrections/Wotlk/wotlkItemFixes.lua, Database/Corrections/Wotlk/wotlkQuestFixes.lua
Fixes #4325
- Added objective data for quest
=> [quest] fixes for 12979

Database/Corrections/Wotlk/wotlkNPCFixes.lua
Fixes #4382
Fixes #3922
- Added location data for quest
=> [quest] added location data for 13121

Database/Corrections/QuestieItemBlacklist.lua
May help with this, not sure. 
https://github.com/Questie/Questie/issues/4427
=> Adding a few items that drop all over to ignore list

Modules/FramePool/QuestieFrame.lua, Modules/Map/HBDHooks.lua, Modules/Map/QuestieMap.lua, Modules/Network/QuestieComms.lua, Modules/QuestieEventHandler.lua, Modules/QuestiePlayer.lua, Modules/Tooltips/Tooltip.lua
=> Minor performance improvements

Modules/QuestieCompat.lua
Fixes #4626
- Fix Dragonflight API mapping
TODOs:
- This is not the case (anymore?)
- No `nil` check required, but it doesn't hurt either
=> [fix] Fix auto questing after Dragonflight API update

Modules/FramePool/QuestieFrame.lua
Fixes https://github.com/Questie/Questie/issues/4899
=> Shift+Lclick to link quests

Database/Corrections/tbcQuestFixes.lua
4 quests in BEM and 2 in Isle of Quel'danas were creating issues
=> Fixes #4806 Misc Quest Fixes causing Load and Validation Warning trigger

Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/classicItemFixes.lua, Database/Corrections/classicNPCFixes.lua, Database/Corrections/classicQuestFixes.lua, Database/Corrections/tbcNPCFixes.lua, Database/Corrections/tbcQuestFixes.lua, Database/Corrections/wotlkNPCFixes.lua, Localization/Translations/ExtraObjectives/ClassicObjectives.lua
Added and fixed various missing objectives
=> Teldrassil and Darkshore quests

Modules/QuestieInit.lua, Modules/QuestiePlayer.lua
=> Fixed level check for daily filtering

Localization/Translations/Zones/EasternKingdoms.lua, Localization/Translations/Zones/Northrend.lua
adds missing translation (Ahn'kahet) and fixes one (Tirisfal Glades)
=> [locale] fix for Tirisfal Glade(s) and Ahn'kahet

.luacheckrc, .vscode/settings.json, Modules/QuestieNameplate.lua
Allows Questie icons to work with AzeriteUI
=> [fix] add support for AzeriteUI target frame

.luacheckrc, .vscode/settings.json, Modules/Quest/QuestEventHandler.lua, Modules/Quest/QuestieQuest.lua, Modules/QuestieInit.lua, Modules/QuestieProfiler.lua, Modules/Tracker/QuestieTracker.lua, Modules/Tracker/TrackerLinePool.lua, Modules/Tracker/TrackerQuestFrame.lua
Removed deprecated scroll frame templates and implemented the new ones introduced in patch 3.4.2
- Updated Questie Tracker scroll frames to use new API's
- Updated Questie Profiler scroll frames to use new API's
- Updated Questie Quest debug strings and moved them from SPAM to INFO
- Updated Questie Tracker formatting to adjust for various offsets to scroll frames
- Fixed an issue with trackerQuestPadding
=> [fix] Fix for new ScrollFrameTemplate

Database/Corrections/wotlkNPCFixes.lua
=> [db] Corrected coords for Midsummer NPCs in Stormwind

Database/QuestieDB.lua, Modules/Quest/QuestieQuest.lua
Each commit will contain details for issues addressed.
=> Misc Bug Fixes for June 26th

Modules/Quest/QuestEventHandler.lua
- Each commit will contain details for issues addressed.
=> Misc Bug Fixes for June 27th

Modules/Options/TrackerTab/QuestieOptionsTracker.lua, Modules/Tracker/QuestieTracker.lua
Fixes #5010 
Details are either in the individual commits or the linked issues.
=> Misc Fixes for June 29th

Modules/Libs/QuestieLib.lua, Modules/Quest/QuestEventHandler.lua, Modules/Quest/QuestLogCache.lua, Modules/Quest/QuestieQuest.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/Tooltips/Tooltip.lua, Modules/Tracker/QuestieTracker.lua
Change details are noted in each commit or linked issue.
=> Misc fixes July 17

Database/QuestXP/QuestieXP.lua, Modules/QuestieInit.lua
=> [fix] Adjust quest XP accordingly if "Joyous Journeys" is active

Modules/Tooltips/MapIconTooltip.lua
Fixes #
-
-
Before:
With the fix:
=> [fix] Fix map icon tooltips not showing multiple objectives

Modules/Quest/QuestieQuest.lua
=> [fix] Fix lua error when turning in quests which are turn in only (e.g. Timbermaw feathers)

Modules/Quest/QuestieQuest.lua
=> [fix] Fix turn in only quests not getting marked as complete

Modules/Journey/tabs/QuestsByZone/QuestsByZoneTab.lua
=> [fix] Fix current zone detection for "Quests by Zone"

Modules/Journey/QuestieSearchResults.lua
=> [fix] Fix zone names not being translated in Journey search results

.types/data/Quest.t.lua, Database/Classic/classicQuestDB.lua, Database/Corrections/wotlkQuestFixes.lua, Database/QuestieDB.lua, Database/TBC/tbcQuestDB.lua, Database/Wotlk/wotlkQuestDB.lua, Database/questDB.lua, Modules/Libs/QuestieLib.lua
=> Add requiredMaxLevel field

.types/data/Quest.t.lua, Database/QuestieDB.lua, Modules/Journey/QuestDetailsFrame.lua, Modules/Journey/QuestieJourneyPrivates.lua, Modules/Journey/QuestieSearchResults.lua, Modules/Journey/tabs/MyJourney/MyJourney.lua, Modules/Journey/tabs/QuestsByZone/QuestsByZone.lua, Modules/Libs/QuestieLib.lua, Modules/Map/QuestieMap.lua, Modules/Network/QuestieComms.lua, Modules/Quest/QuestEventHandler.lua, Modules/Quest/QuestieQuest.lua, Modules/QuestLinks/Link.lua, Modules/Tooltips/MapIconTooltip.lua, Modules/Tooltips/Tooltip.lua, Modules/Tracker/QuestieTracker.lua, Modules/Tracker/TrackerMenu.lua, Modules/Tracker/TrackerUtils.lua
=> Minor DB improvement

Localization/Translations/MinimapIcon/MinimapIcon.lua
=> [locale] Add translation for "Questie will open after combat ends."

Modules/Quest/QuestieQuest.lua
=> [quest] Hide child quests if their exclusiveTo is in the quest log

Modules/FramePool/QuestieFrame.lua, Modules/Options/IconsTab/QuestieOptionsIcons.lua, Modules/Quest/QuestieQuest.lua
=> [fix] Fix SoD rune quests showing even with the option disabled

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
https://github.com/Questie/Questie/issues/5327
Fixes #5327
- ADDED: 'Wild Wyvern Wrangling' is now in the QuestDB, and should be accessible to users.
=> ADDED: Added 'Wild Wyvern Wrangling' (78114) To SoM QuestDB

Modules/Tracker/TrackerUtils.lua
=> Fix GetQuestLogCompletionText does not exist on 1.14.2 issue

Database/Corrections/Automatic/sodBaseQuests.lua, Database/QuestieDB.lua, Database/compiler.lua, Modules/Options/AdvancedTab/QuestieOptionsAdvanced.lua, Modules/Options/QuestieOptionsDefaults.lua, Modules/QuestieInit.lua, Modules/QuestieMenu.lua
=> Store separate SoD database

Database/Corrections/Automatic/sodBaseQuests.lua, Database/Corrections/sodQuestFixes.lua
Fixes #
- Add "Shifting Scale Talisman" quest
Not related to any rune.  
Used the quest_data.lua generated from the scraper.
Added required source item from BFD to start the quest
Put ratchet as the zone similarly to other ratchet related quests
=> Add "Shifting Scale Talisman" quest

Database/Corrections/sodNPCFixes.lua
N/a
- ADDED: Comments to make clear what IDs link to which NPCs. Should make it easier in the future for devs to modify them if necessary without requiring a lookup on them.
=> [npc] ADDED: Comments To Make Clear What IDs Link To

Database/Corrections/sodNPCFixes.lua
Fixes #5547
- ADDED: Proper Coordinates For Kazragore When In Horde Base To NPCDB
=> [npc] ADDED: Proper Coordinates For Kazragore When In Horde Base To NPCDB

Database/Corrections/sodObjectFixes.lua
- ADDED: Comments to all object fixes to enable easier access to names of each object within the `sodObjectFixes.lua` file.
=> [quest] ADDED: Comments To Object Fixes

Database/Corrections/sodNPCFixes.lua, Database/Corrections/sodQuestFixes.lua
- ADDED: Comments to all quest fixes to enable easier access to names of each item within the `sodQuestFixes.lua` file.
=> [quest] ADDED: Comments To Quest Fixes

Database/Corrections/sodNPCFixes.lua
N/a
- ADDED: New Spawn Locations For Zandalarian Emissary
- MODIFIED: Style in `sodNPCFixes.lua` To Be Consistent
=> [npc] ADDED: Zandalarian Emissary Spawn Locations

Localization/Translations/WeaponSkills.lua
Fixes #5678
- ADDED: Polearms to weapon skills l10n.
=> [translations] ADDED: Polearms To Translation Table

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
=> [quest] Add Shaman's "Spirit of the Alpha" rune

Database/Corrections/sodQuestFixes.lua
N/a
- ADDED: triggerEnd override to Gnomer-gooooone! to stop errors on load
=> [quest] ADDED: triggerEnd To SoD Gnomer-goooone!

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5707 
Linked To #5636 
- ADDED: 'Steady Shot' Hunter fake rune quests
=> [quest] Add Hunters 'Steady Shot' rune

Database/Corrections/sodQuestFixes.lua
N/a
- ADDED: startedBy & finishedBy overrides to Gnogaine to show on map
=> [quest] ADDED: Gnogaine NPC Override

Database/Corrections/sodItemFixes.lua
#5716 
- ADDED: Additional NPCs to npcDrops attribute to reduce errors.
=> [item] ADDED: Spent Voidcore npcDrops Attribute Override

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua, Database/QuestieDB.lua
Fixes #5812 
- ADDED: 'Gale Winds' Druid fake rune quest
=> [quest] Add 'Gale Winds' Druid Fake Rune Quest

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5845 
- ADDED: 'Burn' Shaman fake rune quest
=> [quest] Add 'Burn' Shaman Fake Rune Quest

Modules/QuestieMenu/QuestieMenu.lua
Fixes #5894
- Added Archaeology icon
- Moved Archaeology to secondary professions
=> [fix] Added Archaeology icon and moved it to secondary professions

Modules/Quest/QuestLogCache.lua
=> [fix] Correctly handle invalid API responses with empty objectives

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodObjectFixes.lua, Database/Corrections/sodQuestFixes.lua, Database/QuestieDB.lua
Fixes #5891 
- ADDED: 'Taste for Blood' Warrior fake rune quest
=> [quest] Add 'Taste for Blood' Warrior Fake Rune Quest

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
Fixes #5924 
- ADDED: 'Improved Barkskin' Druid fake rune quest
=> [quest] Add 'Improved Barkskin' Druid Fake Rune Quest

Modules/Tooltips/Tooltip.lua, Modules/Tooltips/Tooltip.test.lua
Fixes #4948
- [The previous fix](https://github.com/Questie/Questie/commit/52944ba8ac04542925e368bac0d73ffa8ea3014b) caused that users won't see the progress of  group members, when the user has already completed the objective
-
=> [fix] Proper fix for not showing objective tooltips on finishing NPCs

.github/ISSUE_TEMPLATE/quest_issue.md
Fixes # N/A
- Adds a link to https://wowhead.com/cata into the list of Wowhead links.
N/A
=> Update the issue template to add Cata to the Wowhead links

Database/Zones/zoneDB.lua, Database/Zones/zoneDB.test.lua, Modules/Tooltips/Tooltip.lua, Modules/Tooltips/Tooltip.test.lua
=> [fix] Fix object tooltips showing quests from other zones

Database/Corrections/cataQuestFixes.lua
Fixes #6138
- Add a fix to include prerequisite quest for Tell 'Em Koko Sent You
=> [quest] Fix 'Tell 'Em Koko Sent You' Prerequisite

Database/Corrections/cataQuestFixes.lua
Fixes #6139
- Add a fix to include correct objectives for Arcane Legacy
=> [quest] Fix 'Arcane Legacy' Objectives

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
- Add 'Elune's Fires' Druid P3 SoD Rune Quest
=> [quest] Add 'Elune's Fires' Druid Fake Rune Quest

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
- Add 'Displacement' Mage P3 SoD Rune Quest
=> [quest] Add 'Displacement' Mage Fake Rune Quest

Database/Corrections/sodQuestFixes.lua
Fixes #6126
- Add a fix to two chromatic quests to be flagged as repeatable
=> [quest] Fix Chromatic Quests Now Flagged As Repeatable

Database/Corrections/sodQuestFixes.lua
- Add 'Fanaticism' Paladin P3 SoD Rune Quest
=> [quest] Add 'Fanaticism' Paladin Rune Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6133
- Add a fix to include triggerEnd for Death from Below as done in 'Missing In Action' & 'Supplies to Auberdine'.
=> [quest] Fix 'Death from Below' triggerEnd

Database/Corrections/cataQuestFixes.lua
Fixes #6132 
- Add a fix to include triggerEnd for Goggle Boggle as done in 'Missing In Action' & 'Supplies to Auberdine'.
=> [quest] Fix 'Goggle Boggle' triggerEnd

Database/Corrections/cataQuestFixes.lua
Fixes #6159
- Add a fix to prerequisite quest for the 'Ethel Rethor' quest.
=> [quest] Fix 'Ethel Rethor' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6083
- Add a fix to zoneOrSort for the 'Aberrations of Bone' quest.
=> [quest] Fix 'Aberrations of Bone' Zone Sort

Database/Corrections/cataQuestFixes.lua
Fixes #6172
- Add a fix to prerequisite quest for the 'Taking Part' quest.
=> [quest] Fix 'Taking Part' Prerequisite Quest

Database/Corrections/SeasonOfDiscovery.lua, Database/Corrections/sodQuestFixes.lua
- Add 'Hammer of the Righteous' Paladin P3 SoD Rune Quest
=> [quest] Add 'Hammer of the Righteous' Paladin Rune Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6168
- Add a fix to `objectives` for the 'Wetter Than Wet' quest.
=> [quest] Fix 'Wetter Than Wet' Objectives

Database/Corrections/cataQuestFixes.lua
Fixes #6220
- Add `preQuestSingle` to the 'Tears of Stone' quest.
=> [quest] Add 'Tears of Stone' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6222 
- Add `preQuestSingle` to the 'Report to Silvia' quest.
=> [quest] Add 'Report to Silvia' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6246
- Add `preQuestSingle` to the 'Taming The Tamers' quest.
=> [quest] Add 'Taming The Tamers' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6239
- Add `preQuestSingle` to the 'Building Your Own Coffin' quest.
=> [quest] Add 'Building Your Own Coffin' Prerequisite Quest

Database/Corrections/cataQuestFixes.lua
Fixes #6169
- Add a fix to `objectives` for the 'Deep Impact' quest.
=> [quest] Fix 'Deep Impact' Objectives

Database/Corrections/cataQuestFixes.lua
Fixes #6229
- Add `preQuestSingle` to the 'Tell Silvia'' quest.
=> [quest] Add 'Tell Silvia' Prerequisite Quest

Database/Corrections/sodQuestFixes.lua
-Fixes "The Wild Gods" zoneOrSort field and updates it to Felwood instead of Uknown Zone
=> "The Wild Gods" Quest Correction in sodQuestFixes [82043]

Database/Corrections/cataQuestFixes.lua
Also added faction markers for this quest and the alliance quest of the same name.
Fixes #6159
=> [quest] Added 14255 - Ethel Rethor (Horde)

Database/Corrections/cataQuestFixes.lua
Add necessary prequests 5421 and 14334.
Fixes #6449
=> [quest] Add 14335 Chipping In

Database/Corrections/cataQuestFixes.lua
=> [quest] Added 25329 Might of the Stonemaul

Database/Corrections/cataQuestFixes.lua
Added prerequisite quest 25368 Verinias the Twisted
=> [quest] Added 25645 Return To Sage Palerunner

Database/Corrections/cataQuestFixes.lua
Also fixed the alliance version (25396) of the quest.
Fixes #6461
=> [quest] 25237 Tears of Stone - added

Database/Corrections/QuestieQuestBlacklist.lua
https://www.wowhead.com/cata/quest=10218/someone-elses-hard-work-pays-off
Fixes #6432
=> [quest] Remove 10218 from Cata

Database/Corrections/cataQuestFixes.lua
Marked as breadcrumb quest for 25067 Thunderdrome: The Ginormus!
=> [quest] Mark "The Thunderdrome!" as breadcrumb quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Booty Duty - correct prequest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Grand Tablet - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Twilight Mystery - added prequest

Database/Corrections/cataQuestFixes.lua
Also removed exclusion of other quest
Fixes #6474
=> [quest] Harpy Lieutenants - removed prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Adventures in Archaeology - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Shaper's Terrace - added prequest

Database/Corrections/cataQuestFixes.lua
=> [quest] Speak With Spraggle - marked as breadcrumb quest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Sunveil Excursion - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] False Idols & Neptool's Revenge - added prequest

Database/Corrections/cataQuestFixes.lua
=> [quest] Bonechewer Blood - fixed prerequisite quests

Database/Corrections/cataQuestFixes.lua
Made it a breadcrumb quest instead.
Fixes #6540
=> [quest] Pool of Tears - removed unnecessary prequest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Heart of the Temple - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Harpy Raiders - removed unnecessary prerequisite quest

Database/Corrections/cataQuestFixes.lua
Also add breadcrumb quest.
Make this quest a breadcrumb for Futile Pride.
Fixes #6552
=> [quest] Okrilla and the Blasted Lands - remove prequest

Database/Corrections/cataQuestFixes.lua
Add prerequisite quest
Fixes #6547
Fixes #6549
Fixes #6550
=> [quest] Tides Of Darkness, Reinforcements Denied, Marking The Fallen

Database/Corrections/cataQuestFixes.lua
=> [quest] Neeka Bloodscar - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] We're Under Attack! - added prerequisite quests

Database/Corrections/cataQuestFixes.lua
=> [quest] Chips off the Old Block, Damn You, Frostilicus - add prequest

Database/Corrections/cataQuestFixes.lua
=> [quest] Starfall Village - add prequest, mark as breadcrumb quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Kilram's Boast - add prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] The Pursuit Of Umbranse - add prerequisite quests

Database/Corrections/cataQuestFixes.lua
=> [quest] The Owlbeasts' Defense - added prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Where There's Smoke, There's Delicious Meat

Database/Corrections/cataQuestFixes.lua
=> [quest] Falling to Corruption - remove prerequisite quest

Database/Corrections/cataQuestFixes.lua
=> [quest] Screechy Keen - add prerequisite quest

Database/Corrections/cataNPCFixes.lua
=> [db] Shy-Rotam - fix location

Database/Corrections/cataQuestFixes.lua
=> [quest] Into the Mountain - add prerequisite quests

Database/Corrections/cataQuestFixes.lua
=> [quest] Enhancing the Stone - add prerequisite quests

Database/Corrections/cataQuestFixes.lua
Fixes #6596
Fixes #6597 
Fixes #6598
=> [quest] The Amulet of Allistarj / Sevine / Grol - add prerequisite quest

Database/Corrections/cataItemFixes.lua
=> [db] The Amulet of Sevine - assign to correct NPC

Database/Corrections/cataQuestFixes.lua
=> [quest] Strange Energy - remove prerequisite quests

Database/Corrections/cataQuestFixes.lua
=> [quest] Return to Thrallmar - fix quest giver

Database/Corrections/cataQuestFixes.lua
Also fix objective's text.
Fixes #6623
=> [quest] Postponing the Inevitable - fix NPC, remove prequest

Database/Corrections/cataQuestFixes.lua
Also fix objective's text
Fixes #6628
=> [quest] Prisoner of War - fix NPC, remove prequest

Database/Corrections/cataNPCFixes.lua
Also improve formatting
Fixes #6634
=> [db] Captured Tuskarr Prisoner - fix location

Database/Corrections/cataNPCFixes.lua
=> [db] Longrunner Proudhoof - fix location

Database/Corrections/cataNPCFixes.lua
=> [db] Wartook Iceborn - fix location

Database/Corrections/cataNPCFixes.lua
=> [db] Elder Harkek - fix location

Database/Corrections/BlacklistFilter.lua, Database/Corrections/BlacklistFilter.test.lua, Database/Corrections/Holidays/QuestieEvent.lua
=> [fix] Fix event quests being hidden for wrong expansion

Localization/Translations/Options/Icons.lua, Localization/Translations/Options/Map.lua, Localization/Translations/Options/Minimap.lua
=> Locale updates

Localization/Translations/MinimapIcon/MinimapIcon.lua
=> translation update

README.md
- Correct Chinese to Simplified Chinese and Taiwanese to Traditional Chinese.
=> [Misc.] Correction of language distinction

Localization/Translations/Options/DBMHud.lua
Fixes #6872
- Fix typo in DBMHud.
-
=> [Locale] Fix typo.

Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/cataQuestFixes.lua
Fixes #
- Fix breadcrumb quests
- Update objectives for Heroes of Darrowshire
- Blacklist quests removed with Cata
=> [quest] Cata EPL Horde Quest Fixes

Localization/lookups/Classic/lookupItems/lookupItems.xml, Localization/lookups/Classic/lookupNpcs/lookupNpcs.xml, Localization/lookups/Classic/lookupObjects/lookupObjects.xml, Localization/lookups/Classic/lookupQuests/lookupQuests.xml
This fucks with me :D
Should not be a problem because the file is actually named frFR not frFr.
=> Fix the incorrect filename of frFr to frFR

Database/Corrections/QuestieQuestBlacklist.lua, Database/Corrections/mopItemFixes.lua, Database/Corrections/mopNPCFixes.lua, Database/Corrections/mopObjectFixes.lua, Database/Corrections/mopQuestFixes.lua, Localization/Translations/ExtraObjectives/MopObjectives.lua
=> Kun lai quest fixes

Modules/Quest/QuestFinisher.lua, Modules/Quest/QuestFinisher.test.lua, Modules/Tooltips/Tooltip.lua, Modules/Tooltips/Tooltip.test.lua, Modules/Tooltips/TooltipHandler.lua, Modules/Tooltips/TooltipHandler.test.lua
=> Object tooltips refactor

Modules/Quest/DailyQuests/DailyQuests.lua, Modules/Quest/DailyQuests/DailyQuests.test.lua, Modules/Quest/DailyQuests/QuestHubs.lua
=> Exclusive hubs
